<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, height=device-height">
<meta name="viewport" content="width=device-width; initial-scale=1.0">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<title>Denefits</title>
<link rel="shortcut icon" href="/front-end/images/favicon.ico" type="image/x-icon">
<link rel="icon" href="/front-end/images/favicon.ico" type="image/x-icon">

<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400;300' rel='stylesheet' type='text/css'>

<link href="/front-end/css/style.css" rel="stylesheet">
<!--[if IE]><script src="assets/jscript/html5.js"></script><![endif]-->
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
<div class="wrapper">
<header>
	<div class="logo"><a href="/" title="denefits"><img src="/front-end/images/logo.png" width="260" height="79" alt="Logo"></a></div>  
    <div class="menu">
    	<div class="green-button"><a href="javascript:void(0);" title="Get Your Plan">Get Your Plan</a></div>
        <div class="icon-close">
            <img src="/front-end/images/close.png" width="22" height="22" alt="Close">
        </div>
        <div class="denefit-text">1-800-DENEFITS</div>
        <ul>
            <li><a href="javascript:void(0);" title="The Difference">The Difference</a></li>
            <li><a href="javascript:void(0);" title="Find My Plan">Find My Plan</a></li>
            <li><a href="javascript:void(0);" title="Our Network">Our Network</a></li>
            <li><a href="javascript:void(0);" title="Compliance">Compliance</a></li>
            <li><a href="/dashboardfront/riskreferrals" title="Risk Refferals">Risk Refferals</a></li>
            <li><a href="/dashboardfront/doctordashboard" title="Doctor Dashboard">Doctor Dashboard</a></li>
            <li><a href="/dashboardfront/features" title="Feature">Feature</a></li>
            <li><a href="/dashboardfront/pricing" title="Pricing">Pricing</a></li>
            <li><a href="/dashboardfront/contact" title="Contact Us">Contact Us</a></li>
            <li><a href="/dashboardfront/workwithus" title="Work With Us">Work With Us</a></li> 
            <li><a href="javascript:void(0);" title="Press">Press</a></li>
            <li><a href="javascript:void(0);" title="Blog">Blog</a></li>
        </ul>
    </div>
    <div class="icon-menu">
        <ul>
        	<li><a href="javascript:void(0);" title="Provider"><span class="provider-icon"></span>Provider</a></li>
            <li><a href="/admin/1" title="Login"><span class="login-icon"></span>Login</a></li>
            <li class="burger-menu"><i class="fa fa-bars"></i> <span class="menu-text">Menu</span></li>
        </ul>
    </div>
    <div id="menu">
    	<div class="logo"><a href="index.html" title="denefits"><img src="/front-end/images/logo.png" width="260" height="79" alt="Logo"></a></div>  
        <div class="icon-menu">
            <ul>
                <li><a href="javascript:void(0);" title="Provider"><span class="talk-icon"></span>Talk With a Guide</a></li>
                <li class="quote-button"><a href="javascript:void(0);" title="Get a Quote">Get a Quote</a></li>
            </ul>
        </div>
    </div>
</header>
<div class="container">
	<div class="row">
		<div class="banner">
        	<h1><span>Hi, we're denefits.</span><br/>The word's first private dental<br/> plan market place.</h1>
            <div class="green-button started"><a href="javascript:void(0);" title="Get Your Plan to Get Me Started ">Get Your Plan to Get Me Started </a></div>
            <div class="denefit-textb">1-800-DENEFITS</div>
        </div>
    </div>
</div>
<div class="grid100" id="better">
    <div class="arrow-wrapper">
    	<div class="arrow-container">
            <div class="down-arrow"><a href="#better" title="Down">Arrow</a></div>
            <!--<div class="up-arrow"><a href="#home" title="Up">Arrow</a></div>-->
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="cost-process">
                <h2>Better care, lower cost</h2>
                <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis arcu sit amet dui lacinia, at pretium massa congue. Etiam facilisis tellus at leo aliquet vulputate. </p>
                <ul>
                    <li>
                        <div class="process-banner"><img src="/front-end/images/quote-banner.png" width="203" height="188" alt="Banner"></div>
                        <h3>Compare Your Quote</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis arcu sit amet dui lacinia, at pretium massa congue. Etiam </p>
                        <a href="javascript:void(0);" title="Learn More">Learn More</a>
                    </li>
                    <li>
                        <div class="process-banner"><img src="/front-end/images/price-banner.png" width="129" height="177" alt="Banner"></div> 
                        <h3>Name Your Price</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis arcu sit amet dui lacinia, at pretium massa congue. Etiam </p>
                        <a href="javascript:void(0);" title="Learn More">Learn More</a>
                    </li>
                    <li>
                        <div class="process-banner"><img src="/front-end/images/teethie-banner.png" width="198" height="184" alt="Banner"></div> 
                        <h3>Take a Teethie</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis arcu sit amet dui lacinia, at pretium massa congue. Etiam </p>
                        <a href="javascript:void(0);" title="Learn More">Learn More</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>    
</div>

<div class="grid100" id="modern"> 
	<div class="arrow-wrapper">
    	<div class="arrow-container">
            <div class="down-arrow"><a href="#modern" title="Down">Arrow</a></div>
            <!--<div class="up-arrow"><a href="#better" title="Up">Arrow</a></div>-->
        </div>
    </div>  
    <div class="container">
        <div class="row">
   	  		<div class="column grid50 paddingRight50">
            	<h4>Modern technology for modern care</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis arcu sit amet dui lacinia, at pretium massa congue. Etiam facilisis tellus at leo aliquet vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis arcu sit amet dui lacinia, at pretium massa congue. Etiam facilisis tellus at leo aliquet vulputate.</p>
            </div>
            <div class="grid50 mobile-banner">
            	<img src="/front-end/images/modern-banner.png" width="586" height="318" alt="Banner">
            </div>
    	</div>
    </div>    
</div>      

<div class="grid100" id="denefits">   
	<div class="arrow-wrapper">
    	<div class="arrow-container">
            <div class="down-arrow"><a href="#denefits" title="Down">Arrow</a></div>
            <!--<div class="up-arrow"><a href="#modern" title="Up">Arrow</a></div>-->
        </div>
    </div>
    <div class="container">
        <div class="row">
   	  		<div class="grid50 mobile-banner">
            	<img src="/front-end/images/denefit-banner.png" width="496" height="332" alt="Banner">
            </div>
            <div class="column grid50 paddingRight50">
            	<h4>Denefits is for everyone<br/><span>(Individuals, Couples, and Families)</span></h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis arcu sit amet dui lacinia, at pretium massa congue. Etiam facilisis tellus at leo aliquet vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis arcu sit amet dui lacinia, at pretium massa congue. Etiam facilisis tellus at leo aliquet vulputate.</p>
            </div>
    	</div>
    </div>    
</div>  

<div class="grid100" id="help">   
	<div class="arrow-wrapper">
    	<div class="arrow-container">
            <div class="down-arrow"><a href="#help" title="Down">Arrow</a></div>
            <!--<div class="up-arrow"><a href="#denefits" title="Up">Arrow</a></div>-->
        </div>
    </div>
    <div class="container">
        <div class="row">
   	  		<div class="column grid50 paddingRight50">
            	<h4>Help us make Dental plan simple, smart, and friendly</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis arcu sit amet dui lacinia, at pretium massa congue. Etiam facilisis tellus at leo aliquet vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis arcu sit amet dui lacinia, at pretium massa congue. Etiam facilisis tellus at leo aliquet vulputate.</p>
            </div>
            <div class="grid50 mobile-banner">
            	<img src="/front-end/images/dental-banner.png" width="370" height="370" alt="Banner">
            </div>
    	</div>
    </div>    
</div>         

<div class="testimonial-frame">
	<div class="container">
        <div class="row column align-center">
        	<h4>See what others are saying about denefits</h4>
        </div>
        <ul>
        	<li>
            	<h5>Lorem Ipsum dolor </h5>
                <p>Wliquam sit amet urna sed vel nullam semper aibe vestibulum fringilla orem ipsum dolor sit amet con sectetur adipisicing elit sed don eiusmod tempor incididunt ut labore et dolore.</p>
                <div class="user-frame">
                	<div class="img-holder"><img src="/front-end/images/user.png" width="55" height="55" alt="User"></div>
                    <div class="detail">
                    	<h6>kyle joseph</h6>
                        <p>DOCTOR</p>
                        <div class="quote"><img src="/front-end/images/quote.png" width="36" height="31" alt="Quote"></div>
                    </div>
                </div>
            </li>
            <li>
            	<h5>Lorem Ipsum dolor </h5>
                <p>Wliquam sit amet urna sed vel nullam semper aibe vestibulum fringilla orem ipsum dolor sit amet con sectetur adipisicing elit sed don eiusmod tempor incididunt ut labore et dolore.</p>
                <div class="user-frame">
                	<div class="img-holder"><img src="/front-end/images/user.png" width="55" height="55" alt="User"></div>
                    <div class="detail">
                    	<h6>kyle joseph</h6>
                        <p>DOCTOR</p>
                        <div class="quote"><img src="/front-end/images/quote.png" width="36" height="31" alt="Quote"></div>
                    </div>
                </div>
            </li>
            <li>
            	<h5>Lorem Ipsum dolor </h5>
                <p>Wliquam sit amet urna sed vel nullam semper aibe vestibulum fringilla orem ipsum dolor sit amet con sectetur adipisicing elit sed don eiusmod tempor incididunt ut labore et dolore.</p>
                <div class="user-frame">
                	<div class="img-holder"><img src="/front-end/images/user.png" width="55" height="55" alt="User"></div>
                    <div class="detail">
                    	<h6>kyle joseph</h6>
                        <p>DOCTOR</p>
                        <div class="quote"><img src="/front-end/images/quote.png" width="36" height="31" alt="Quote"></div>
                    </div>
                </div>
            </li>
        </ul>
    </div>    
</div>
<div class="zip-frame">
    <div class="container">
        <div class="row">
            <form class="zip-wrapper">
                <fieldset>
                    <label for="zipcode">My zip code is</label>
                    <input type="text" name="zipcode" id="zipcode" placeholder="10012">
                    <div class="green-button started"><a href="javascript:void(0);" title="Get Your Plan in Seconds">Get Your Plan in Seconds</a></div>
                </fieldset>
            </form>
        </div>
    </div>
</div>      
<footer>
    <div class="container">
        <div class="row">
            <div class="footer-menu">
                <ul>
                    <li>Discover</li>
                    <li><a href="javascript:void(0);" title="Better Plans">Better Plans</a></li>
                    <li><a href="javascript:void(0);" title="Better Care">Better Care</a></li>
                    <li><a href="javascript:void(0);" title="Better Experience">Better Experience</a></li>
                </ul>
                <ul>
                    <li>Explore</li>
                    <li><a href="javascript:void(0);" title="Search Doctors">Search Doctors</a></li>
                    <li><a href="javascript:void(0);" title="Search Drugs">Search Drugs</a></li>
                    <li><a href="javascript:void(0);" title="Find Forms">Find Forms</a></li>
                </ul>
                <ul>
                    <li>Sign Up</li>
                    <li><a href="javascript:void(0);" title="Get Your Free Quote">Get Your Free Quote</a></li>
                    <li><a href="javascript:void(0);" title="Talk with a Guide">Talk with a Guide</a></li>
                    <li><a href="javascript:void(0);" title="View Plan Highlights">View Plan Highlights</a></li>
                </ul>
                <ul>
                    <li>Company</li>
                    <li><a href="javascript:void(0);" title="About Us">About Us</a></li>
                    <li><a href="javascript:void(0);" title="Careers">Careers</a></li>
                    <li><a href="javascript:void(0);" title="Blog">Blog</a></li>
                </ul>
                <ul>
                    <li>Partners</li>
                    <li><a href="javascript:void(0);" title="Brokers">Brokers</a></li>
                    <li><a href="javascript:void(0);" title="Providers">Providers</a></li>
                    <li><a href="javascript:void(0);" title="Press">Press</a></li>
                </ul>
            </div>
            <div class="terms-frame">
                <div class="bottom-wrapper">
                    <p><span><a href="privacy_policy.html" title="Privacy Policy">Privacy Policy</a> | <a href="terms_use.html" title="Terms of Use">Terms of Use</a></span> &copy; 2016 denefits.com. All Rights Reserved.</p>
                    <ul class="social-links">
                        <li><a href="javascript:void(0);" title="Facebook"><span class="social-icon facebook"></span></a></li>
                        <li><a href="javascript:void(0);" title="Twitter"><span class="social-icon twitter"></span></a></li>
                        <li><a href="javascript:void(0);" title="Linkedin"><span class="social-icon pinterest"></span></a></li>
                        <li><a href="javascript:void(0);" title="Google Plus"><span class="social-icon google"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>    
</footer>
</div>
<script src="/front-end/jscript/jquery.min.js"></script>
<script src="/front-end/jscript/jquery-custom.js"></script> 
</body>
</html>

