
<!-- Page content -->
<div id="page-content">
    <!-- Forms Components Header -->
    <div class="content-header">
        <div class="row">
            <div class="col-sm-6">
                <div class="header-section">
                    <h1> <h1><?php if($plan_id) { echo "Edit"; } else { echo "Add";}?> Plan Details</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- END Forms Components Header -->

    <!-- Form Components Row -->
    <div class="row">
        <div class="col-md-12">
            <!-- Horizontal Form Block -->
            <div class="block">
               <!-- General Elements Content -->
                <form action="" method="post" class="form-horizontal form-bordered">
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="example-text-input">Name</label>
                        <div class="col-md-6">
                            <input type="text" id="plan_name" name="plan_name" class="form-control" placeholder="Name" value="<?php echo $plans[0]['plan_name'];?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="example-text-input">Individual Price (Monthly / Annually)</label>
                        <div class="col-md-6">
                            <input type="text" id="plan_monthly_price" name="plan_monthly_price" class="smalltxt" placeholder="Individual Price Monthly" value="<?php echo $plans[0]['plan_monthly_price'];?>">&nbsp;&nbsp;&nbsp;<input type="text" id="plan_yearly_price" name="plan_yearly_price" class="smalltxt" placeholder="Individual Price Annually" value="<?php echo $plans[0]['plan_yearly_price'];?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="example-text-input">Addon Price (Monthly / Annually)</label>
                        <div class="col-md-6">
                            <input type="text" id="addon_monthly_price" name="addon_monthly_price" class="smalltxt" placeholder="Addon Price Monthly" value="<?php echo $plans[0]['addon_monthly_price'];?>">&nbsp;&nbsp;&nbsp;<input type="text" id="addon_yearly_price" name="addon_yearly_price" class="smalltxt" placeholder="Addon Price Annually" value="<?php  echo $plans[0]['addon_monthly_price'];?>">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="example-text-input">Heading Line</label>
                        <div class="col-md-6">
                            <input type="text" id="heading_line" name="heading_line" class="form-control" placeholder="Heading Line" value="<?php echo $plans[0]['heading_line'];?>">
                        </div>
                    </div>
<?php if($plan_id) { ?>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Services</label>
                        <div class="col-md-9">
                            <p class="form-control-static"> <?php if($plan_services){
    foreach($plan_services as $ps):  ?>
             <b><?php echo $ps['service_type']; ?></b>&nbsp;&nbsp;&nbsp;&nbsp;<a href="/dashboardfront/plansservice/<?php echo  $plans[0]['plan_id']."/".$ps['service_id']; ?>">Edit</a><br /> 
                                <?php for($i=1;$i<=10;$i++) { if($ps["service_name$i"]){ ?>
                                <i><?php echo $ps["service_name$i"];?></i><br>
                                <?php }} ?>
                                <i><?php echo $ps['service_notes'];?></i><br>
                                <?php endforeach; ?>
    <?php }else{ ?>                         
        <a href="/dashboardfront/plansservice/<?php echo $plan_id ;?>">add new</a>                     
                                <?php } ?></p>
                        </div>
                    </div>
<?php } ?>
                    <div class="form-group form-actions">
                        <div class="col-md-9 col-md-offset-3">
                            <button type="submit" class="btn btn-effect-ripple btn-primary">Submit</button>
                            <button type="reset" class="btn btn-effect-ripple btn-danger" onclick="javascript: window.location.assign('/dashboardfront/plan')">Cancel</button>
                            <a href="/dashboardfront/delplan/<?php echo $plans[0]['plan_id'];?>" data-toggle="tooltip" onclick="return confirm('Are you sure you want to delete this Plan?');"><button type="reset" class="btn btn-effect-ripple btn-danger">Delete</button></a>
                        </div>
                    </div>
                <input type="hidden" name="pid" value="<?php echo $plan_id;?>" />
                <input type="hidden" id="doc_id" name="doc_id" class="form-control" placeholder="Name" value="<?php echo @$doc_id;?>">
                </form>
                <!-- END General Elements Content -->

            </div>
        
    </div>
    <!-- END Form Components Row -->
</div>
<!-- END Page Content -->
