<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, height=device-height">
<meta name="viewport" content="width=device-width; initial-scale=1.0">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<title>Denefits</title>
<link rel="shortcut icon" href="/front-end/images/favicon.ico" type="image/x-icon">
<link rel="icon" href="/front-end/images/favicon.ico" type="image/x-icon">

<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400;300' rel='stylesheet' type='text/css'>

<link href="/front-end/css/style.css" rel="stylesheet">
<!--[if IE]><script src="assets/jscript/html5.js"></script><![endif]-->
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
<div class="wrapper">
<header>
    <div class="logo"><a href="/" title="denefits"><img src="/front-end/images/logo.png" width="260" height="79" alt="Logo"></a></div>  
    <div class="menu">
        <div class="green-button"><a href="javascript:void(0);" title="Get Your Plan">Get Your Plan</a></div>
        <div class="icon-close">
            <img src="/front-end/images/close.png" width="22" height="22" alt="Close">
        </div>
        <div class="denefit-text">1-800-DENEFITS</div>
       <ul>
            <li><a href="javascript:void(0);" title="The Difference">The Difference</a></li>
            <li><a href="javascript:void(0);" title="Find My Plan">Find My Plan</a></li>
            <li><a href="javascript:void(0);" title="Our Network">Our Network</a></li>
            <li><a href="javascript:void(0);" title="Compliance">Compliance</a></li>
            <li><a href="/dashboardfront/riskreferrals" title="Risk Refferals">Risk Refferals</a></li>
            <li><a href="/dashboardfront/doctordashboard" title="Doctor Dashboard">Doctor Dashboard</a></li>
            <li><a href="/dashboardfront/features" title="Feature">Feature</a></li>
            <li><a href="/dashboardfront/pricing" title="Pricing">Pricing</a></li>
            <li><a href="/dashboardfront/contact" title="Contact Us">Contact Us</a></li>
            <li><a href="/dashboardfront/workwithus" title="Work With Us">Work With Us</a></li> 
            <li><a href="javascript:void(0);" title="Press">Press</a></li>
            <li><a href="javascript:void(0);" title="Blog">Blog</a></li>
        </ul>
    </div>
    <div class="icon-menu">
        <ul>
            <li><a href="javascript:void(0);" title="Provider"><span class="provider-icon"></span>Provider</a></li>
            <li><a href="/admin/1" title="Login"><span class="login-icon"></span>Login</a></li>
            <li class="burger-menu"><i class="fa fa-bars"></i> <span class="menu-text">Menu</span></li>
        </ul>
    </div>
    <div id="menu">
        <div class="logo"><a href="index.html" title="denefits"><img src="/front-end/images/logo.png" width="260" height="79" alt="Logo"></a></div>  
        <div class="icon-menu">
            <ul>
                <li><a href="javascript:void(0);" title="Provider"><span class="talk-icon"></span>Talk With a Guide</a></li>
                <li class="quote-button"><a href="javascript:void(0);" title="Get a Quote">Get a Quote</a></li>
            </ul>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <div class="banner">
            <h1><span>Simple Pricing </span><br/>$300/mo</h1>
        </div>
    </div>
</div>
<div class="grid100">
    <div class="container">
        <div class="row">
            <div class="feature-process">
                <ul>
                    <li>
                        <div class="process-banner"><img src="/front-end/images/dentist-banner.png" width="151" height="174" alt="Banner"></div>
                        <h3>See the Dentist you Want</h3>
                        <p>Unhappy with your current doc, then we will help you find another one, If you love your current dentist, then never leave him because of insurance complications.</p>
                    </li>
                    <li>
                        <div class="process-banner"><img src="/front-end/images/interest-banner.png" width="156" height="177" alt="Banner"></div> 
                        <h3>Aligned Interests</h3>
                        <p>Being part of your dentist's private plan aligns both your interests. Dentists won't want to do unnecessary treatment when they have to pay for it as well.</p>
                    </li>
                    <li>
                        <div class="process-banner"><img src="/front-end/images/bill-banner.png" width="170" height="171" alt="Banner"></div> 
                        <h3>No Surprise Bills</h3>
                        <p>No middle man. No surprise denials or downgrades of needed dental treatment. Get 100% accurate pricing from your dentist all the time.</p>
                    </li>
                    <li>
                        <div class="process-banner"><img src="/front-end/images/exam-banner.png" width="68" height="185" alt="Banner"></div>
                        <h3>Unlimited Exams and Xrays</h3>
                        <p>Don't worry about having to pay every time a dentist sees you. Good dental health for you means less work for the dentist.</p>
                    </li>
                    <li>
                        <div class="process-banner"><img src="/front-end/images/coverage-banner.png" width="122" height="179" alt="Banner"></div> 
                        <h3>100% Coverage for cleanings</h3>
                        <p>Get the proper amount of cleanings you need to keep you healthy. If you need 4 cleanings a year, you will get 4 cleanings a year</p>
                    </li>
                    <li>
                        <div class="process-banner"><img src="/front-end/images/online-banner.png" width="115" height="166" alt="Banner"></div> 
                        <h3>Check your benefits online</h3>
                        <p>See for yourself what still needs to be done. You never have to call to see if you still have treatment pending</p>
                    </li>
                    <li>
                        <div class="process-banner"><img src="/front-end/images/upgrade-banner.png" width="215" height="182" alt="Banner"></div>
                        <h3>Upgrade Anytime</h3>
                        <p>Once you have enrolled in your private dental plan, add your family for a low discounted rate. You can upgrade your plan anytime.</p>
                    </li>
                    <li>
                        <div class="process-banner"><img src="/front-end/images/secure-banner.png" width="182" height="175" alt="Banner"></div> 
                        <h3>100% Secure Online Patient Financing</h3>
                        <p>Finance any treatment with your dentist. Change your payment info anytime. Check your balance. Pay extra if you want to. Request to pay less if you need to as well!</p>
                    </li>
                    <li>
                        <div class="process-banner"><img src="/front-end/images/message-banner.png" width="168" height="181" alt="Banner"></div> 
                        <h3>Secure Messaging</h3>
                        <p>100% secure HIPAA compliant messaging with your dentist! No more searching through your cluttered inbox to find previous communication. Message through our app!</p>
                    </li>
                    <li>
                        <div class="process-banner"><img src="/front-end/images/teeth-banner.png" width="184" height="147" alt="Banner"></div>
                        <h3>Teeth Whitening</h3>
                        <p>Seriously, have you ever heard of a dental insurance company having teeth whitening as a benefit? Our dentists include cosmetic teeth whitening in their plans.</p>
                    </li>
                    <li>
                        <div class="process-banner"><img src="/front-end/images/app-banner.png" width="78" height="147" alt="Banner"></div> 
                        <h3>The Denefits App</h3>
                        <p>Communicate with your dentist on your own time. No need to call and leave voice messages. Check your financing, upgrade, change your info. All in one place. </p>
                    </li>
                    <li>
                        <div class="process-banner"><img src="/front-end/images/compliance-banner.png" width="205" height="145" alt="Banner"></div> 
                        <h3>Compliance</h3>
                        <p>Don't depend on a dentist's own system to keep your information secured. Security is not their specialty. Their cost cutting is a violation of HIPAA and PCI compliance and will leave you picking up the pieces.</p>
                    </li>
                </ul>
                <div class="green-button started"><a href="javascript:void(0);" title="Get Me Started ">Get Me Started </a></div>
                <div class="blue-button clearboth started"><a href="javascript:void(0);" title="Have a Questions?">Have a Questions?</a></div>
                <div class="denefit-textb">1-800-DENEFITS</div>
            </div>
        </div>
    </div>    
</div>

     
<footer>
    <div class="container">
        <div class="row">
            <div class="footer-menu">
                <ul>
                    <li>Discover</li>
                    <li><a href="javascript:void(0);" title="Better Plans">Better Plans</a></li>
                    <li><a href="javascript:void(0);" title="Better Care">Better Care</a></li>
                    <li><a href="javascript:void(0);" title="Better Experience">Better Experience</a></li>
                </ul>
                <ul>
                    <li>Explore</li>
                    <li><a href="javascript:void(0);" title="Search Doctors">Search Doctors</a></li>
                    <li><a href="javascript:void(0);" title="Search Drugs">Search Drugs</a></li>
                    <li><a href="javascript:void(0);" title="Find Forms">Find Forms</a></li>
                </ul>
                <ul>
                    <li>Sign Up</li>
                    <li><a href="javascript:void(0);" title="Get Your Free Quote">Get Your Free Quote</a></li>
                    <li><a href="javascript:void(0);" title="Talk with a Guide">Talk with a Guide</a></li>
                    <li><a href="javascript:void(0);" title="View Plan Highlights">View Plan Highlights</a></li>
                </ul>
                <ul>
                    <li>Company</li>
                    <li><a href="javascript:void(0);" title="About Us">About Us</a></li>
                    <li><a href="javascript:void(0);" title="Careers">Careers</a></li>
                    <li><a href="javascript:void(0);" title="Blog">Blog</a></li>
                </ul>
                <ul>
                    <li>Partners</li>
                    <li><a href="javascript:void(0);" title="Brokers">Brokers</a></li>
                    <li><a href="javascript:void(0);" title="Providers">Providers</a></li>
                    <li><a href="javascript:void(0);" title="Press">Press</a></li>
                </ul>
            </div>
            <div class="terms-frame">
                <div class="bottom-wrapper">
                    <p><span><a href="privacy_policy.html" title="Privacy Policy">Privacy Policy</a> | <a href="terms_use.html" title="Terms of Use">Terms of Use</a></span> &copy; 2016 denefits.com. All Rights Reserved.</p>
                    <ul class="social-links">
                        <li><a href="javascript:void(0);" title="Facebook"><span class="social-icon facebook"></span></a></li>
                        <li><a href="javascript:void(0);" title="Twitter"><span class="social-icon twitter"></span></a></li>
                        <li><a href="javascript:void(0);" title="Linkedin"><span class="social-icon pinterest"></span></a></li>
                        <li><a href="javascript:void(0);" title="Google Plus"><span class="social-icon google"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>    
</footer>
</div>
<script src="/front-end/jscript/jquery.min.js"></script>
<script src="/front-end/jscript/jquery-custom.js"></script> 
</body>
</html>