<?php
// plan cycle
$plan_billing_cycle[1] = 'Monthly';
$plan_billing_cycle[2] = 'Annually';

$plan_bill_cycle[1] = 'Month';
$plan_bill_cycle[2] = 'Year';


// gender type
$sex[1] = 'Male';
$sex[2] = 'Female';


// plan type
$plan_type[1] = 'Individual';
$plan_type[2] = 'Family';
$plan_type[3] = 'Addon';
?>

<!-- Page content -->
<div id="page-content">
    <!-- Table Styles Header -->
    <div class="content-header">
        <div class="row">
            <div class="col-sm-6">
                <div class="header-section">
                    <h1>Patients&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<!--<small>Active: <?php echo $act_pats;?></small>&nbsp;&nbsp;&nbsp;<small>Inactive: <?php echo $inact_pats;?></small>--></h1>
                </div>
                
            </div>
            <div class="col-sm-6 hidden-xs">
                <div class="header-section">
                    <ul class="breadcrumb breadcrumb-top">
                     <!--   <li><a href="/dashboardfront/planchoise" class="btn btn-effect-ripple btn-primary" data-toggle="tooltip" data-placement="left" title="" style="overflow: hidden; position: relative;" data-original-title="Add new patient">Add new patient</a></li>  -->
                    </ul>
                </div>
            </div> 
        </div>
    </div>
    <!-- END Table Styles Header -->
    <!-- Datatables Block -->
    <!-- Datatables is initialized in js/pages/uiTables.js -->
	<?php if($del_message) { ?>
        <div class="row">
			<div class="col-sm-12">
				<div class="alert alert-success alert-dismissable">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
						<h4><strong>Success</strong></h4>
						<p>Record Deleted successfully!</p>
				</div>
			</div>
		</div>
	<?php } ?>
	<?php if($_GET['refered']==1) { ?>
        <div class="row">
			<div class="col-sm-3">
				<div class="alert alert-success alert-dismissable">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
						<h4><strong>Success</strong></h4>
						<p>Patient referred successfully!</p>
				</div>
			</div>
		</div>
	<?php } 
    ?>


    <div class="block full">
        <div class="table-responsive">
            <table id="example-datatable" class="table table-striped table-bordered table-vcenter">
                <thead>
                    <tr>
                        <th class="text-center" style="width: 30px;">ID</th>
                        <th>Name</th>
                        <th>Age</th>
                        <th>Sex</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th style="width: 130px;">Refered Status</th>
                        <th class="text-center" style="width: 85px;"><i class="fa fa-flash"></i></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $labels['0']['class'] = "label-danger";
                    $labels['0']['text'] = "Pending";
                    $labels['1']['class'] = "label-success";
                    $labels['1']['text'] = "Accepted";
					// get list of plans for this doctor
					foreach($listPatient as $listPatientvalue){
						unset($phone);
						if($listPatientvalue['patient_phone']) 
							$phone[] = $listPatientvalue['patient_phone'];
						if($listPatientvalue['patient_mobile']) 
							$phone[] = $listPatientvalue['patient_mobile'];

    // check plan type
    $plantype = '';
    $i =0;$arr=array();
        foreach($listonlyPatient as $listPatientvalueinner)
        {
        // echo  ",".$listPatientvalueinner['parent_id']." ".$listPatientvalue['patient_id'].'<br>' ;
         if(($listPatientvalueinner['parent_id'])==($listPatientvalue['patient_id'])){
          //  $plantype = $plan_type[2]; 
             $arr[$i++]=$listPatientvalueinner['patient_id'] ;
         }
        }
    if(count($arr)>0){
     $plantype = $plan_type[2]; 
    }
  if($listPatientvalue['parent_id']>0) {
	$plantype = $plan_type[3];
    }
  if($plantype=='')
 $plantype = $plan_type[1];
					?>
                    <tr>
                        <td class="text-center"><?php echo $listPatientvalue['patient_id']; ?></td>
                        <td><?php echo $listPatientvalue['patient_firstname'].' '.$listPatientvalue['patient_lastname']; ?></td>
                        <td><?php echo (date('Y')-date('Y',strtotime($listPatientvalue['patient_dob']))); ?></td>
                        <td><?php echo $sex[$listPatientvalue['patient_sex']]; ?></td>
                        <td><?php echo $listPatientvalue['patient_email']; ?></td>
                        <td><?php if(is_array($phone)) { echo implode(' / ',$phone); } else echo $phone; ?></td>
                        <td><span class="label<?php echo " " . $labels[$listPatientvalue['patient_status']]['class']; ?>"><?php echo $labels[$listPatientvalue['patient_status']]['text']; ?></span>
                       </td>
                        <td class="text-center">
							<a href="/dashboardfront/specilistviewpatient/<?php echo $listPatientvalue['patient_id'];?>" data-toggle="tooltip" title="View Patient" class="btn btn-effect-ripple btn-xs btn-info"><i class="fa fa-laptop"></i></a>
							<a href="/dashboardfront/specilistpatientrefer/<?php echo $listPatientvalue['patient_id'];?>" data-toggle="tooltip" title="Refer Patient" class="btn btn-effect-ripple btn-xs btn-info"><i class="fa fa-check"></i></a>
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
    <!-- END Datatables Block -->
</div>
<!-- END Page Content -->
   <script src="/js/pages/uiTables.js"></script>
<script>$(function(){ UiTables.init(); });</script>