<div class="row">
   <?php 
 if ($this->flashMessenger()->hasMessages()) {
    echo '<div class="alert alert-info">';
    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }
   echo '</div>';
}
?>
</div>
<div style="background:#F7F7F7;height:470px;">
        <a class="hiddenanchor" id="toregister"></a>
        <a class="hiddenanchor" id="tologin"></a>
        <div id="wrapper">
          <div id="login" class="animate form" style="min-width:500px;">
              <section class="login_content">
    <?php
        $form->setAttribute('onsubmit', 'return false');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formElement($form->get('rid')); 
    ?>
             <h1 style="color:#1B75BA;width:360px">Edit Role Permission</h1>
                <div  style="margin-left:0px;">
                    <?php echo $this->formElement($form->get('role')); ?>
                </div>
                <div  style="margin-left:-31px;">
                 <h1 style="color:#666666;font-size:14px;">Check For Giving Permission</h1>
                 <div style="width:100%;float:left;">
           

    <style type="text/css">
       code {
            white-space: nowrap;
            color:transparent;
            }
    </style>

    <!-- start tree configuration -->
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.3.js"></script>
    <script type="text/javascript"
            src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <link rel="stylesheet" type="text/css"
          href="https://code.jquery.com/ui/1.11.4/themes/ui-lightness/jquery-ui.css"/>
<!--
    <script type="text/javascript" src="minified/jquery.tree.min.js"></script>
    <link rel="stylesheet" type="text/css" href="minified/jquery.tree.min.css"/>
    <!-- end tree configuration -->

    <!-- start development configuration -->

    <script type="text/javascript" src="/src/js/jquery.tree.js"></script>
    <link rel="stylesheet" type="text/css" href="/src/css/jquery.tree.css"/>

    <!-- start development configuration -->

    <script type="text/javascript">
        //<!--
        $(document).ready(function() {
            $( "#accordion" ).accordion({
                'collapsible': false,
                'active': null,
                'heightStyle': 'content'
            });
            $('.jquery').each(function() {
                eval($(this).html());
            });
            $('.button').button();
        });
        //-->
    </script>
<div id="accordion" >
      <h3></h3>
        <div id="example-0">
     
            <code style="background-color:transparent;height:5px;" class="jquery" lang="text/javascript">
                $('#example-0 div').tree({
                });
            </code>
            <div>
                <ul>
                     <?php
                          foreach($allclientsdetail as $clientsdetail => $clientsdetailvalue) 
                          {                                                    // clientloop start here
                      ?>
                    <li style="text-align:left;"><input type="checkbox"><span><?php  echo strtoupper($clientsdetailvalue['client_name'])  ; ?></span>
                        <ul>
                         <?php
                          foreach($allcategorydetail as $categorydetail => $categorydetailvalue) 
                             {                                                    // categoryloop start here
                          ?>
                         <li><input type="checkbox"><span><?php echo $categorydetailvalue['category_name']  ; ?></span>
                                <ul>
                                   <?php    
                                    foreach($permission as $permissionname =>$permissionvalue)
                                     {  
                                                 $clientidArray= explode(',',$permissionvalue['client_id']) ;
                                                 $id_clienttable = $clientsdetailvalue['id'] ;
                                                 $id_categorytable = $categorydetailvalue['id'] ;
                                                 $flagloop = 0 ;
                                                 foreach($rolepermission as $rolepermissionname => $rolepermissionvalue) 
                                                    {   
                                                   if($rolepermissionvalue['permission_id']==$permissionvalue['id'])
                                                     {
                                                     $flagloop = 1 ;
                                                     }
                                                   }
                                                 if((in_array($id_clienttable,$clientidArray))&&($id_categorytable==$permissionvalue['cat_id'])){
                                                      if($flagloop==1){
                                                  ?>
                                                <li>
                                          <input type="checkbox" value="<?php  echo $permissionvalue['id'] ; ?>" name="chkbox" id="chkbox" checked><?php  echo $permissionvalue['permission_name'] ; ?>
                                                </li>
                                                <?php 
                                               }else{
                                               ?>
                                              <li>
                                             <input type="checkbox" name="chkbox" id="chkbox" value="<?php  echo $permissionvalue['id'] ; ?>"><?php  echo $permissionvalue['permission_name'] ; ?>
                                              </li>
                                            <?php
                                            }  //  if else close here 
                                       }   // if of permission loop close here
                                     }    //permission  loop close here 
                                    ?>
                                </ul>
                            </li>
                            <?php
                              }  //category loop close here 
                              ?> 
                        </ul>
                   </li> 
                <?php
                    }  //client loop close here 
                ?>                         
        </ul>
      </div>
    </div>
 </div>













       <!--          
        <?php    
         foreach($permission as $permissionname =>$permissionvalue)
          {  
          $flagloop = 0 ;
           foreach($rolepermission as $rolepermissionname => $rolepermissionvalue) 
            {   
             if($rolepermissionvalue['permission_id']==$permissionvalue['id']){
               $flagloop = 1 ;
                  }
                }
              if($flagloop==1){
                ?>
              <div class="checkbox" style="width:161px;float:left;margin-top:0px;text-align:left;padding-left:20px;">
                   <label><input type="checkbox" value="<?php  echo $permissionvalue['id'] ; ?>" name="chkbox" id="chkbox" checked><?php  echo $permissionvalue['permission_name'] ; ?></label>
               </div> 
                   <?php 
                     }else{
                    ?>
                    <div class="checkbox" style="width:161px;float:left;margin-top:0px;text-align:left;padding-left:20px;">
                    <label><input type="checkbox" name="chkbox" id="chkbox" value="<?php  echo $permissionvalue['id'] ; ?>"><?php  echo $permissionvalue['permission_name'] ; ?></label>
                   </div>
                <?php
                 }  //  if else close here 
              }  // permission loop close here 
         ?> 


              -->
                  </div>
              </div>
                      <div style="margin-left:15px;">
                        <?php
                             echo $this->formSubmit($form->get('submit'));
                        ?>
                        <a class="reset_pass" href="<?php echo  $this->url('dashboard', array('action' => 'viewroles')) ; ?>">Cancel</a> 
                     
                        </div>
                        <div class="clearfix"></div>
                        <div class="separator">
                        <div class="clearfix"></div>
                            <br />
                       </div>
                   
                    <!-- form -->
                </section>
                <!-- content -->
            </div>
         </div>
    </div>





















































