
<div class="row">
   <?php 

if ($this->flashMessenger()->hasMessages()) {
    echo '<div class="alert alert-info">';
    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }
  echo '</div>';
}

?>
</div>

 <div style="background:#F7F7F7;height:470px;">
        <a class="hiddenanchor" id="toregister"></a>
        <a class="hiddenanchor" id="tologin"></a>

        <div id="wrapper">
            <div id="login" class="animate form">
                <section class="login_content">
<?php $form->setAttribute('onsubmit', $this->url('dashboard', array('action' => 'editclients','id'=>$id)));
         $form->prepare();
         echo $this->form()->openTag($form);
         echo $this->formHidden($form->get('id'));
?>
                        <h1 style="color:#1B75BA;width:360px">Edit Client Form</h1>
                         <div>
                          <?php echo $this->formElement($form->get('clientname')); ?>
                        </div>
                      
                         <div>
                        </div>
                        <div style="margin-top:10px;">
                           <?php
                             echo $this->formSubmit($form->get('submiteditclients'));
                           ?>
                   <a class="reset_pass" href="<?php echo  $this->url('dashboard', array('action' => 'viewcategory')) ; ?>">Cancel</a>
                        </div>
                        <div class="clearfix"></div>
                        <div class="separator">
                        <div class="clearfix"></div>
                            <br />
                       </div>
                   
                    <!-- form -->
                </section>
                <!-- content -->
            </div>
         </div>
    </div>





































