<?php

$title = 'My Dashboard';
//$this->headTitle($title);
//<!DOCTYPE HTML>

?>
<!-- Page content -->
<div id="page-content">
    <!-- Table Styles Header -->
    <div class="content-header">
        <div class="row">
            <div class="col-sm-6">
                <div class="header-section">
                    <h1>Plans</h1>
                </div>
            </div>
<div class="col-sm-6 hidden-xs">
                <div class="header-section">
                    <ul class="breadcrumb breadcrumb-top">
                        <li><a data-original-title="Add New Plan" style="overflow: hidden; position: relative;" title="" data-placement="left" data-toggle="tooltip" class="btn btn-effect-ripple btn-primary" href="/dashboard/plan_edit/0/<?php echo $doc_id; ?>">Add New Plan</a></li>                       
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- END Table Styles Header -->
    <!-- Datatables Block -->

    <div class="block full">
        <div class="table-responsive">
            <table id="example-datatable" class="table table-striped table-bordered table-vcenter">
                <thead>
                    <tr>
                        <th class="text-center" style="width:auto;">ID</th>
                        <th class="text-center" style="width:auto;">Name</th>
                        <th class="text-right" style="width:auto;">Individual Price (Monthly / Annually)</th>
						<th class="text-right" style="width:auto">Addon Price (Monthly / Annually)</th>
						  <th class="text-center" style="width:auto;"><i class="fa fa-flash"></i></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($plans as $plan): ?>
                    <tr>
						 <td class="text-center"  style="width:auto;"><?php echo $plan['plan_id'];?></td>
                        <td class="text-center"  style="width:auto;"><?php echo $plan['plan_name'];?></td>
                        <td class="text-right"  style="width:auto;"><?php echo $plan['plan_monthly_price']."/".$plan['plan_yearly_price'];?></td>
						<td class="text-right"  style="width:auto;"><?php echo $plan['addon_monthly_price']."/".$plan['addon_yearly_price'];?></td>
						<td class="text-center">
							<a href="/dashboard/plan_view/<?php echo $plan['plan_id']."/".$doc_id;?>" data-toggle="tooltip" title="View Plan" class="btn btn-effect-ripple btn-xs btn-info"><i class="fa fa-laptop"></i></a>
                            <a href="/dashboard/plan_edit/<?php echo $plan['plan_id']."/".$doc_id;?>" data-toggle="tooltip" title="Edit Plan" class="btn btn-effect-ripple btn-xs btn-success"><i class="fa fa-pencil"></i></a>
                            <a href="/dashboard/plan_delete/<?php echo $plan['plan_id']."/".$plan['doc_id'];?>" data-toggle="tooltip" title="Delete Plan" class="btn btn-effect-ripple btn-xs btn-danger" onclick="return confirm('Are you sure you want to delete this Plan?');"><i class="fa fa-times"></i></a>
                        </td>
                    </tr>
                  <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <!-- END Datatables Block -->
</div>
<!-- END Page Content -->
<script type="text/javascript">$.fn.dataTable.ext.errMode = 'none';</script>











