<!-- Page content -->
<div id="page-content">
    <!-- Table Styles Header -->
    <div class="content-header">
        <div class="row">
            <div class="col-sm-6">
                <div class="header-section">
                    <h1>Services</h1>
                </div>
            </div>
            <div class="col-sm-6 hidden-xs">
                <div class="header-section">
                    <ul class="breadcrumb breadcrumb-top">
                        <li><a href="spl_service_edit.php" class="btn btn-effect-ripple btn-primary" data-toggle="tooltip" data-placement="left" title="" style="overflow: hidden; position: relative;" data-original-title="Create new plan">Add new service</a></li>
                    </ul>
                </div>
            </div>

        </div>
    </div>
    <!-- END Table Styles Header -->
    <!-- Datatables Block -->
    <!-- Datatables is initialized in js/pages/uiTables.js -->
	

<?php
$flashMessage = $this->flashMessenger()->getMessages();
if (count($flashMessage)) {
 ?>
<?php
    foreach ($flashMessage as $msg){
        foreach ($msg as $type => $message) {
             ?>
         <div class="row">
            <div class="col-sm-12">
                <div class="alert alert-success alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                        <h4><strong>Success</strong></h4>
                        <p>Record Deleted successfully!</p>
                </div>
            </div>
        </div>
        <?php
           }
         }
     
     }
 ?>

    <div class="block full">
        <div class="table-responsive">
            <table id="example-datatable" class="table table-striped table-bordered table-vcenter">
                <thead>
                    <tr>
                        <th class="text-center" style="width: 50px;">ID</th>
                        <th>Service Name</th>
                        <th>Price</th>
                        <th class="text-center" style="width: 75px;"><i class="fa fa-flash"></i></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
					// get list of plans for this doctor
					foreach($splServices as $spls_r) { 
					?>
                    <tr>
                        <td class="text-center"><?php echo $spls_r['service_id']; ?></td>
                        <td><?php echo $spls_r['service_type']; ?></td>
                        <td><?php echo $spls_r['price']; ?></td>
                        <td class="text-center">
							<a href="/dashboard/specialservicedetail/<?php echo $spls_r['service_id'];?>" data-toggle="tooltip" title="View Service" class="btn btn-effect-ripple btn-xs btn-info"><i class="fa fa-laptop"></i></a>
                            <a href="/dashboard/specialserviceedit/<?php echo $spls_r['service_id'];?>/<?php echo $spls_r['doc_id'];?>" data-toggle="tooltip" title="Edit Service" class="btn btn-effect-ripple btn-xs btn-success"><i class="fa fa-pencil"></i></a>
                            <a href="/dashboard/deletespecialservice/<?php echo $spls_r['service_id'];?>/<?php echo $spls_r['doc_id'];?>" data-toggle="tooltip" title="Delete Service" class="btn btn-effect-ripple btn-xs btn-danger" onclick="return confirm('Are you sure you want to delete this Service?');"><i class="fa fa-times"></i></a>
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
    <!-- END Datatables Block -->
</div>
<!-- END Page Content -->


<!-- Load and execute javascript code used only in this page -->
<script src="js/pages/uiTables.js"></script>
<script>$(function(){ UiTables.init(); });</script>
<script type="text/javascript">$.fn.dataTable.ext.errMode = 'none';</script>
