

        <!-- Main Sidebar -->
<div id="sidebar">
    <!-- Sidebar Brand -->
    <div id="sidebar-brand" class="themed-background">
        <a href="/dashboardfront/welcome" class="sidebar-title">
           <img src="/img/logo.png" align="Dental Plan" width="100%" height="100%" /><!-- <i class="fa fa-cube"></i> <span class="sidebar-nav-mini-hide">Dental Plan</span>-->
        </a>
    </div>
    <!-- END Sidebar Brand -->

    <!-- Wrapper for scrolling functionality -->
    <div id="sidebar-scroll">
        <!-- Sidebar Content -->
        <div class="sidebar-content">
                        <!-- Sidebar Navigation -->
            <ul class="sidebar-nav">
                <li>
                    <a href="/dashboardfront/welcome"  <?php if($_SERVER['REQUEST_URI']=='/dashboardfront/welcome'){ ?> class=" active" <?php  } ?> ><i class="gi gi-compass sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Dashboard</span></a>
                </li>
                <li class="sidebar-separator">
                    <i class="fa fa-ellipsis-h"></i>
                </li>
                <li>
                    <a href="/dashboardfront/patient"  <?php if($_SERVER['REQUEST_URI']=='/dashboardfront/patient'){ ?> class=" active" <?php  } ?>><i class="fa fa-rocket sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Manage Patients</span></a>
                </li>
                                                                <li>
                    <a href="/dashboardfront/plan" <?php if($_SERVER['REQUEST_URI']=='/dashboardfront/plan'){ ?> class=" active" <?php  } ?>><i class="gi gi-airplane sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Manage Plans</span></a>
                                    </li>
                 <li>
                    <a href="/dashboardfront/docccpay" <?php if($_SERVER['REQUEST_URI']=='/dashboardfront/docccpay'){ ?> class=" active" <?php  } ?> ><i class="gi gi-star sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Billing Information</span></a>
                </li>
                                                                <li>
                    <a href="/dashboardfront/doctoredit" <?php if($_SERVER['REQUEST_URI']=='/dashboardfront/doctoredit'){ ?> class=" active" <?php  } ?>><i class="gi gi-star sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">My Account</span></a>
                                    </li>
                                                                <li>
                    <a href="/dashboardfront/planchoise" <?php if($_SERVER['REQUEST_URI']=='/dashboardfront/planchoise'){ ?> class=" active" <?php  } ?>><i class="gi gi-keys sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Add Patient</span></a>
                                    </li>
                                                                <li>
                    <a href="/dashboardfront/reports"  <?php if($_SERVER['REQUEST_URI']=='/dashboardfront/reports'){ ?> class=" active" <?php  } ?>><i class="gi gi-star sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Reports</span></a>
                                    </li>
                                                                <li>
                    <a href="/dashboardfront/doctorsupport"  <?php if($_SERVER['REQUEST_URI']=='/dashboardfront/doctorsupport'){ ?> class=" active" <?php  } ?>><i class="gi gi-star sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Support</span></a>
                                    </li>
                                            </ul>
            <!-- END Sidebar Navigation -->
                    </div>
        <!-- END Sidebar Content -->
    </div>
    <!-- END Wrapper for scrolling functionality -->


</div>
<!-- END Main Sidebar -->