<!-- Page content -->
<div id="page-content">
    <!-- Forms Components Header -->
    <div class="content-header">
        <div class="row">
            <div class="col-sm-6">
                <div class="header-section">
                    <h1>Service Details</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- END Forms Components Header -->

    <!-- Form Components Row -->
    <div class="row">
        <div class="col-md-12">
            <!-- Horizontal Form Block -->

            <div class="block">
                <!-- General Elements Content -->
                <form action="/dashboard/specialservice/<?php echo $splServicesDetail[0]['doc_id']  ; ?>" method="get" class="form-horizontal form-bordered">
                    <div class="form-group">
                        <label class="col-md-3 control-label">Service Name</label>
                        <div class="col-md-9">
                            <p class="form-control-static"><?php 
                            echo $splServicesDetail[0]['service_type'];?></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Price</label>
                        <div class="col-md-9">
                            <p class="form-control-static"><?php echo $splServicesDetail[0]['price'] ;?></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Services</label>
                        <div class="col-md-9">
                            <p class="form-control-static"><?php 
// get service


        for($i=1;$i<=10;$i++) {
        $servicefield = 'service_name'.$i;
            if(trim($splServicesDetail[0][$servicefield])) {
                echo $splServicesDetail[0][$servicefield].'<br>';
            }
        }
?></p>
                        </div>
                    </div>
                    <div class="form-group form-actions">
                        <div class="col-md-9 col-md-offset-3">
                          <button  type="submit" class="btn btn-effect-ripple btn-primary">Back</button>
                        </div>
                    </div>
                    </form>
                <!-- END General Elements Content -->
            </div>
        
    </div>
    <!-- END Form Components Row -->
</div>
<!-- END Page Content -->



<!-- Load and execute javascript code used only in this page -->
<script src="js/pages/formsComponents.js"></script>
<script>$(function(){ FormsComponents.init(); });</script>
