<!-- Page content -->
<div id="page-content">
    <!-- Table Styles Header -->
    <div class="content-header">
        <div class="row">
            <div class="col-sm-6">
                <div class="header-section">
                    <h1>Support</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- END Table Styles Header -->
    <!-- Datatables Block -->
    <!-- Datatables is initialized in js/pages/uiTables.js -->
    <div class="block full">
        <div class="table-responsive">
            <table id="example-datatable" class="table table-striped table-bordered table-vcenter">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Address</th>
                        <th>Phone</th>
                        <th>Message</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
          // get list of plans for this doctor
           foreach($support as $supportname => $supportvalue){ 
          ?>
            <tr>
             <td><?php echo $supportvalue['first_name'].' '.$supportvalue['last_name']; ?></td>
                        <td><?php echo $supportvalue['email_id']; ?></td>
                        <td><?php echo $supportvalue['address']; ?></td>
                        <td><?php echo $supportvalue['phone']; ?></td>
                        <td><?php echo $supportvalue['message']; ?></td>
                        <td><?php echo date('d-m-Y',strtotime($supportvalue['add_date'])); ?></td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
    <!-- END Datatables Block -->
</div>
<!-- END Page Content -->
