<div class="row">
   <?php 
 if ($this->flashMessenger()->hasMessages()) {
    echo '<div class="alert alert-info">';
    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }
   echo '</div>';
}
?>
</div>
<div style="background:#F7F7F7;height:470px;">
        <a class="hiddenanchor" id="toregister"></a>
        <a class="hiddenanchor" id="tologin"></a>
        <div id="wrapper">
          <div id="login" class="animate form">
              <section class="login_content">
    <?php
        $form->setAttribute('onsubmit', 'return false');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formElement($form->get('rid')); 
    ?>
             <h1 style="color:#1B75BA;width:600px;"><center>View Role And Its Permission<center/></h1>
                
		<div style="margin-left:100px; width:345px;"><div>

                    <span style="font-weight:bold;font-size:16px; color:#757A8D ;">Role Name -</span> <?php echo $rolename ; ?>
                </div>
                <div  style="margin-left:0px;">
                 <span style="font-size:13px;line-height:30px;"><u><span style="color:#8f3d4d;"><i><?php  echo $rolename."&nbsp"; ?></i></span>  has following reports's view permissions</u></span>
                 <div style="width:100%;float:left;">
        <?php    
         foreach($permission as $permissionname =>$permissionvalue)
          {  
          $flagloop = 0 ;
           foreach($rolepermission as $rolepermissionname => $rolepermissionvalue) 
            {   
             if($rolepermissionvalue['permission_id']==$permissionvalue['id']){
               $flagloop = 1 ;
                  }
                }
              if($flagloop==1){
                ?>
              <div class="checkbox" style="width:161px;float:left;margin-top:0px;text-align:left;padding-left:20px;">

                   <label><input type="checkbox" value="<?php  echo $permissionvalue['id'] ; ?>" name="chkbox" id="chkbox" checked disabled><?php  echo $permissionvalue['permission_name'] ; ?></label>
               </div> 
                   <?php 
                     }  
              }  // permission loop close here 
         ?> 
                 </div>
              </div>
                      <div style="margin-left:15px;">
                         <a  href="<?php echo  $this->url('dashboard', array('action' => 'viewroles')) ; ?>">Cancel</a> 
                     </div>
                        <div class="clearfix"></div>
                        <div class="separator">
                        <div class="clearfix"></div>
                            <br />
                       </div>

</div>
                   
                    <!-- form -->
                </section>
                <!-- content -->
            </div>
         </div>
    </div>





















































