
<div class="row">
   <?php 

if ($this->flashMessenger()->hasMessages()) {
    echo '<div class="alert alert-info">';
    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }
  echo '</div>';
}

?>
</div>

 <div style="background:#F7F7F7;height:470px;">
        <a class="hiddenanchor" id="toregister"></a>
        <a class="hiddenanchor" id="tologin"></a>

        <div id="wrapper">
            <div id="login" class="animate form">
                <section class="login_content">
<?php $form->setAttribute('action', $this->url('dashboard', array('action' => 'addreports')));
         $form->prepare();
         echo $this->form()->openTag($form);
         echo $this->formHidden($form->get('id'));
    ?>
                        <h1 style="color:#1B75BA;">Add Reports</h1>
                        
                        <div>
                          <?php echo $this->formElement($form->get('report')); ?>
                        </div>
                        <div align="center" style="width:100%">
                          <?php echo $this->formElement($form->get('reporturl')); ?>
                        </div>
                         
                 <div>
                    <h3 style="color:#757A8D;font-size:18px;">Check For Assign Report To Client</h3>
                    <div style="width:100%;float:left;">
                      <?php    
                       $clients  = $this->clients  ;
                       foreach($clients as $clientsname =>$clientsvalue)
                         {  
                        ?>  
                    <div class="checkbox" style="width:161px;float:left;margin-top:0px;text-align:left;padding-left:20px;">
                     <label><input type="checkbox" value="<?php  echo $clientsvalue['id'] ; ?>" name="chkbox[]" id="chkbox"><?php  echo $clientsvalue['client_name'] ; ?></label>
                    </div> 
                    <?php
                    }  
                     ?> 
                 </div>
              </div>



















                         <div>
                          <?php echo $this->formElement($form->get('cat_id')); ?>
                        </div>
                         <div>
                        </div>
                        <div style="margin-top:10px;">
                         <?php
                             echo $this->formSubmit($form->get('submit'));
                          ?>
<a class="reset_pass" href="<?php echo  $this->url('dashboard', array('action' => 'viewreports')) ; ?>">Cancel</a>
                        </div>
                        <div class="clearfix"></div>
                        <div class="separator">
                        <div class="clearfix"></div>
                            <br />
                       </div>
                   
                    <!-- form -->
                </section>
                <!-- content -->
            </div>
         </div>
    </div>



































