<?php
//echo $ipaddress;
$title = 'My Dashboard';
$this->headTitle($title);

     use Zend\Session\Container;
     $session = new Container('User') ;
     $userrolereports= $session->offsetGet('userrolepermission');






//<!DOCTYPE HTML>
?>

<div style="width:100%;min-height:auto;">

<div style="width:100%;">
</div>
<script type="text/javascript">
window.onload = function() {
//viz.dispose();
var placeholderDiv = document.getElementById("tableauViz");
console.log(placeholderDiv.innerHTML)
var url = "http://54.175.39.22/trusted/<?php echo $tokenno; ?>/views/<?php echo $userrolereports['0']['permission_url'] ; ?>?embed=yes&:display_share=no&:tabs=no&:toolbar=yes&:customViews=no";
var options = {
width: placeholderDiv.offsetWidth,
height: placeholderDiv.offsetHeight,
hideTabs: false,
hideToolbar: false,
onFirstInteractive: function() {

workbook = viz.getWorkbook();

activeSheet = workbook.getActiveSheet();

}

};

console.log(options)

viz = new tableauSoftware.Viz(placeholderDiv, url, options);

};

</script>

<div id="tableauViz" class="fire" style="width:100%; height:1130px; margin-left:25%; visibility:visible;"\"></div>



