<div class="header">
   <div class="logo_container"><img src="/img/mainlogo.png" class="logo" align="left" /></div>
   <div class="tag_container" align="right"><img src="/img/tagline.png" class="tagline" style="margin-right: 20px;"></div>                      
</div>	
   <div><img src="/img/line.png" style="width: 100%; height: 48px;"></div>
<div class="row">
   <?php 
   /*
error_reporting(E_ALL & ~E_NOTICE) ;
if ($this->flashMessenger()->hasMessages()) {
    echo '<div class="alert alert-info">';
    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
     //   echo $message;
      //  echo $message['error'];
    }
  echo '</div>';
}
*/
?>
</div>  
 <div style="background:#F7F7F7;height:470px;">
        <a class="hiddenanchor" id="toregister"></a>
        <a class="hiddenanchor" id="tologin"></a>

        <div id="wrapper">
            <div id="login" class="animate form">
                <section class="login_content">
                          <?php
                          $form->prepare();
                          echo $this->form()->openTag($form);
                         ?>
                        <h1 style="width:500px;margin-left:-70px;">Unlock Login Account Form</h1>
                        <div align="center">
                            <?php echo $this->formElement($form->get('email')); ?>
                       </div>
                        <div>


                            <?php
                            echo $this->formElement($form->get('submit'));
                            echo $this->form()->closeTag($form);
                               ?>
                       
                        </div>
                        <div class="clearfix"></div>
                        <div class="separator">
                        <div class="clearfix"></div>
                            <br />
                       </div>
                   
                    <!-- form -->
                </section>
                <!-- content -->
            </div>
         </div>
    </div>




























