<?php echo $this->doctype(); 
//$stripepath= $_SERVER['DOCUMENT_ROOT']."/stripe/stripephp340/init.php";
//require_once($stripepath);
use Zend\Session\Container;
$session = new Container('User');
$userdatails =array();
$userdatails= $session->offsetGet('userdetail');

?>
<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>denefits</title>
<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon">
<link rel="icon" href="/images/favicon.ico" type="image/x-icon">

<!-- Angular Material style sheet -->
<link href="/css/angular-material.css" rel="stylesheet">
<!-- Custom style sheet -->
   

    <?php 
	 //$session = new Container('User');
	 if($session->offsetExists('email'))
	 {
	 ?>
   <!-- Angular Material requires Angular.js Libraries -->
<script src="/jscript/angular.min.js"></script>
<script src="/jscript/angular-animate.min.js"></script>
<script src="/jscript/angular-aria.min.js"></script>
<script src="/jscript/angular-messages.min.js"></script>

<!-- Angular Material Library -->
<script src="/jscript/angular-material.min.js"></script>  

<?php
}
?>

            
</head>

<!-- header code will start here    -->
<link href="/css/custom.css" rel="stylesheet">                  
<body class="" ng-app="BlankApp" ng-cloak>
<!-- header code will end here    -->
<!-- contant start here    -->
      <?php  echo $this->content;?>
<!-- contant end here    -->
<!-- Angular Material requires Angular.js Libraries -->


    <?php 
	 //$session = new Container('User');
	 if($session->offsetExists('email'))
	 {
	 ?>
                    

<?php
}
?>


<script type="text/javascript">
app.controller('headercontrollar',function($scope,$http,$window)
{
    $scope.switchtext='logon';
    $scope.showbtn=function(text){
        //alert(text);
        if(text=='logon'){
            $scope.switchtext='logoff';
            $window.location.href = '/logout';
        }
    }   
});
</script>
</body>
</html>

