<?php echo $this->doctype(); 
use Zend\Session\Container;
?>
<?php
/**
 * page_header.php
 *
 * Author: pixelcave
 *
 * The header of each page
 *
 */

?>
<header layout="row">
    <div class="logo" layout-align="start" flex><a href="javascript:void(0);" title="denefits"><img src="images/logo.png" width="183" height="57" alt="Logo"></a></div>
    <div class="log-frame" layout-align="start end" flex>Logoff <span class="handle-bar"><i class="handle"></i></span></div>
</header>
  
