
<div class="row">
   <?php 

if ($this->flashMessenger()->hasMessages()) {
    echo '<div class="alert alert-info">';
    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }
  echo '</div>';
}

?>
</div>

 <div style="background:#F7F7F7;height:470px;">
        <a class="hiddenanchor" id="toregister"></a>
        <a class="hiddenanchor" id="tologin"></a>

        <div id="wrapper">
            <div id="login" class="animate form">
                <section class="login_content">
<?php $form->setAttribute('onsubmit', $this->url('dashboard', array('action' => 'editreports','id'=>$id)));
         $form->prepare();
         echo $this->form()->openTag($form);
         echo $this->formHidden($form->get('id'));
?>
                        <h1 style="color:#1B75BA;">Report Edit Form</h1>
                        <div>
                            <?php echo $this->formElement($form->get('report')); ?>
                        </div>
                        <div>
                          <?php echo $this->formElement($form->get('reporturl')); ?>
                        </div>

                <div  style="margin-left:-31px;">
                 <h1 style="color:#666666;font-size:14px;">Check For Giving Permission To Client</h1>
                 <div style="width:100%;float:left;">
        <?php  
      //  echo '<pre>' ;
     //  print_r($reportsdetail);
       $reportsclientidArray  = explode(',',$reportsdetail['0']['client_id']);
         foreach($clientdetail as $clientname =>$clientvalue)
          {  
          $flagloop = 0 ;
           foreach($reportsclientidArray as $reportsclientidname => $reportsclientidvalue) 
            {   
             if($clientvalue['id']==$reportsclientidvalue){
               $flagloop = 1 ;
                  }
                }
              if($flagloop==1){
                ?>
              <div class="checkbox" style="width:161px;float:left;margin-top:0px;text-align:left;padding-left:20px;">
                   <label><input type="checkbox" value="<?php  echo $clientvalue['id'] ; ?>" name="chkbox[]" id="chkbox" checked><?php  echo $clientvalue['client_name'] ; ?></label>
               </div> 
                   <?php 
                     }else{
                    ?>
                    <div class="checkbox" style="width:161px;float:left;margin-top:0px;text-align:left;padding-left:20px;">
                    <label><input type="checkbox" name="chkbox[]" id="chkbox" value="<?php  echo $clientvalue['id'] ; ?>"><?php  echo $clientvalue['client_name']  ; ?></label>
                   </div>
                <?php
                 }  //  if else close here 
              }  // permission loop close here 
         ?> 

                  </div>
              </div>

                         <div>
                          <?php echo $this->formElement($form->get('cat_id')); ?>
                        </div>
                         <div>
                        </div>
                        <div style="margin-top:10px;">
                           <?php
                             echo $this->formSubmit($form->get('submiteditreports'));
                           ?>
                   <a class="reset_pass" href="<?php echo  $this->url('dashboard', array('action' => 'viewreports')) ; ?>">Cancel</a>
                        </div>
                        <div class="clearfix"></div>
                        <div class="separator">
                        <div class="clearfix"></div>
                            <br />
                       </div>
                   
                    <!-- form -->
                </section>
                <!-- content -->
            </div>
         </div>
    </div>





































