<?php
$flashMessage = $this->flashMessenger()->getMessages();
if (count($flashMessage)) {
     echo '<div style="width:100%;height:60px;padding-top:26px;font-family:calibri;font-size:14px;">';
 ?>
<?php
    foreach ($flashMessage as $msg){
        foreach ($msg as $type => $message) {
               echo $message ;
           }
         }
    echo '</div>';     
     }
 ?>
<table class="table table-condensed">

    <thead>
      <tr>
        <th>
      

       <a href="<?php echo $this->url('dashboard',array('action'=>'addcategory')) ; ?>" id="delbutton">   
       	<span class="fa fa-plus-square"><span style="font-size:10px;"> Report Category</span>
       </a>

      </th>
        <th></th>
        <th></th>
      </tr>
       <tr style="width: 100%">
        <th>Serial No.</th>
        <th>Category</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <?php 
      $serialno =1 ;
      foreach($category as $categoryname =>$value) {  
           echo '&nbsp;' ;

        ?>
      <tr>
        <td> <?php  echo  $serialno ; $serialno =$serialno+1 ;  ?></td>
        <td><?php  echo  $value['category_name'] ; ?></td>
        <td>
          <a href="<?php echo $this->url('dashboard',array('action'=>'editcategory','id'=>$value['id'])); ?>"  id="editbutton">
            <span class="glyphicon glyphicon-edit"></span>
          </a>

          

           <a href="#" id="delbutton" onclick="deletecategory('<?php  echo $value['id'] ; ?>')">   <span class="glyphicon glyphicon-trash"></span>
          </a>
        </td>
      </tr>
       <?php
       }
       ?>
    </tbody>
  </table>