
<div class="row" style="margin-top:29px;">
   <?php 

if ($this->flashMessenger()->hasMessages()) {
    echo '<div  class="alert alert-info">';
    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    }
  echo '</div>';
}

?>
</div>


<!-- Page content -->
<div id="page-content"  style="padding-top:0px;">
    <!-- Forms Components Header -->
    <div class="content-header">
        <div class="row">
            <div class="col-sm-6">
                <div class="header-section">
                    <h1>Change Password</h1>
                </div>
            </div>
            
        </div>
    </div>
    <!-- END Forms Components Header -->

    <!-- Form Components Row -->
    <div class="row">

<?php   if($msg==1) { ?>
    <div class="col-md-12">
        <!-- Success Alert -->
        <div class="alert alert-success alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">x</button>
            <h4><strong>Success</strong></h4>
            <p>Password Changed</p>
        </div>
        <!-- END Success Alert -->
    </div>
<?php } elseif($err==1) { ?>
    <div class="col-md-12">
        <!-- Success Alert -->
        <div class="alert alert-danger alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">x</button>
            <h4><strong>Error</strong></h4>
            <p><?php echo $errmsg;?></p>
        </div>
        <!-- END Success Alert -->
    </div>
<?php } ?>
        <div class="col-md-12">
            <!-- Horizontal Form Block -->
            <div class="block">
                <!-- General Elements Content -->
                <form action="/dashboardfront/changepassword" method="post" class="form-horizontal form-bordered">
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="example-text-input">New Password</label>
                        <div class="col-md-6">
                            <input type="password" id="admin_pass" name="admin_pass" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="example-text-input">Confirm Password</label>
                        <div class="col-md-6">
                            <input type="password" id="admin_cpass" name="admin_cpass" class="form-control">
                        </div>
                    </div>
                    <div class="form-group form-actions">
                        <div class="col-md-9 col-md-offset-3">
                            <button type="submit" class="btn btn-effect-ripple btn-primary">Submit</button>
                            <button type="reset" class="btn btn-effect-ripple btn-danger" onclick="javascript: window.location.assign('/dashboardfront/welcome')">Cancel</button>
                        </div>
                    </div>
                </form>
                <!-- END General Elements Content -->
            </div>
        
    </div>
    <!-- END Form Components Row -->
</div>
<!-- END Page Content -->


<!-- ckeditor.js, load it only in the page you would like to use CKEditor (it's a heavy plugin to include it with the others!) -->
<script src="js/plugins/ckeditor/ckeditor.js"></script>

<!-- Load and execute javascript code used only in this page -->
<script src="js/pages/formsComponents.js"></script>
<script>$(function(){ FormsComponents.init(); });</script>

































