<div class="log-frame" layout-align="start end" flex>
	<div class="log-frame" layout-align="start end" ng-controller="headercontrollar" flex>
	<md-switch class="md-primary" md-no-ink ng-model="hasInk" aria-label="No Ink Effects" ng-click="showbtn(switchtext)">
	{{ switchtext }}          
	</md-switch>
</div>

<style>
.log-frame {
    color: #000;
    float: right;
    font-size: 24px;
    line-height: 20px;
    padding: 9px 5px 0 0;
    text-align: right;
    width: auto;
}
</style>
