<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, height=device-height">
<meta name="viewport" content="width=device-width; initial-scale=1.0">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<title>Denefits</title>
<link rel="shortcut icon" href="/front-end/images/favicon.ico" type="image/x-icon">
<link rel="icon" href="/front-end/images/favicon.ico" type="image/x-icon">

<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400;300' rel='stylesheet' type='text/css'>

<link href="/front-end/css/style.css" rel="stylesheet">
<!--[if IE]><script src="assets/jscript/html5.js"></script><![endif]-->
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
<div class="wrapper">
<header>
	<div class="logo"><a href="/" title="denefits"><img src="/front-end/images/logo.png" width="260" height="79" alt="Logo"></a></div>  
    <div class="menu">
    	<div class="green-button"><a href="javascript:void(0);" title="Get Your Plan">Get Your Plan</a></div>
        <div class="icon-close">
            <img src="/front-end/images/close.png" width="22" height="22" alt="Close">
        </div>
        <div class="denefit-text">18885085778</div>
        <ul>
            <li><a href="/dashboardfront/riskreferrals" title="Risk Refferals">No Risk Refferals</a></li>
            <li><a href="/dashboardfront/doctordashboard" title="Doctor Dashboard">Patients</a></li>
            <li><a href="/dashboardfront/features" title="Feature">Features</a></li>
            <li><a href="/dashboardfront/pricing" title="Pricing">Pricing</a></li>
            <li><a href="/dashboardfront/contact" title="Contact Us">Contact Us</a></li>
            <li><a href="/dashboardfront/workwithus" title="Work With Us">Work With Us</a></li> 
        </ul>
    </div>
    <div class="icon-menu">
        <ul>
        	<li><a href="javascript:void(0);" title="Provider"><span class="provider-icon"></span>Patients</a></li>
            <li><a href="/admin/1" title="Login"><span class="login-icon"></span>Login</a></li>
            <li class="burger-menu"><i class="fa fa-bars"></i> <span class="menu-text">Menu</span></li>
        </ul>
    </div>
    <div id="menu">
    	<div class="logo"><a href="index.html" title="denefits"><img src="/front-end/images/logo.png" width="260" height="79" alt="Logo"></a></div>  
    <div class="icon-menu">
        <ul>
            <li><a href="javascript:void(0);" title="Provider"><span class="talk-icon"></span>Talk With a Guide</a></li>
            <li class="quote-button"><a href="/tininsert" title="Get a Quote">Sign Up</a></li>
        </ul>
    </div>
    </div>
</header>
<div class="container">
	<div class="row">
	<div class="banner">
        <h1><span>Simple Pricing </span><br/>$300/mo</h1>
        <div class="green-button started"><a href="/tininsert" title="Sign Up"> Sign Up </a></div>
        <div class="blue-button clearboth started"><a href="javascript:void(0);" title="Have a Questions?">Have a Questions?</a></div>
            <div class="denefit-textb">18885085778</div>
        </div>
    </div>
</div>
<div class="grid100">
    <div class="container">
        <div class="row">
            <div class="feature-process">
                <ul>
                    <li>
                        <div class="feature-list"><img src="/front-end/images/patient-icon.png" width="103" height="77" alt="Banner"></div>
                        <h3><a href="feature-detail.html#patientPortal" title="Patient Portal">Patient Portal</a></h3>
                        <p>Your patients can login and view their coverage, change plans or add family. Patients can see how much coverage they have used and what they have left so or the patient dont...</p>
                    </li>
                    <li>
                        <div class="feature-list"><img src="/front-end/images/doctor-icon.png" width="64" height="87" alt="Banner"></div> 
                        <h3><a href="feature-detail.html#doctorDashboard" title="Doctor Dashboard">Doctor Dashboard</a></h3>
                        <p>Get a full overview of everything that is going on with your practice's Private Dental Plan. Dental Plan Software gives you all the information you need all in one place.</p>
                    </li>
                    <li>
                        <div class="feature-list"><img src="/front-end/images/analytics.png" width="90" height="72" alt="Banner"></div> 
                        <h3><a href="feature-detail.html#fullAnalytics" title="Full Analytics">Full Analytics</a></h3>
                        <p>Get all the numbers of your revenue, patients in each dental plan, accepted or rejected patient referrals and more throughout your own Dental Plan Software account.</p>
                    </li>
                    <li>
                        <div class="feature-list"><img src="/front-end/images/plan-icon.png" width="60" height="84" alt="Banner"></div>
                        <h3><a href="feature-detail.html#unlimitedPlan" title="Create Unlimited Plans">Create Unlimited Plans</a></h3>
                        <p>Your patients can login and view their coverage, change plans or add family. Patients can see how much coverage they have used and what they have left so or the patient dont...</p>
                    </li>
                    <li>
                        <div class="feature-list"><img src="/front-end/images/billing-icon.png" width="91" height="56" alt="Banner"></div> 
                        <h3><a href="feature-detail.html#recurringBilling" title="Recurring Billing">Recurring Billing</a></h3>
                        <p>Get a full overview of everything that is going on with your practice's Private Dental Plan. Dental Plan Software gives you all the information you need all in one place.</p>
                    </li>
                    <li>
                        <div class="feature-list"><img src="/front-end/images/payout-icon.png" width="85" height="77" alt="Banner"></div> 
                        <h3><a href="feature-detail.html#weeklyPayout" title="Weekly Payouts">Weekly Payouts</a></h3>
                        <p>Get all the numbers of your revenue, patients in each dental plan, accepted or rejected patient referrals and more throughout your own Dental Plan Software account.</p>
                    </li>
                    <li>
                        <div class="feature-list"><img src="/front-end/images/system-icon.png" width="73" height="83" alt="Banner"></div>
                        <h3><a href="feature-detail.html#patientManagement" title="Patient Management System">Patient Management System</a></h3>
                        <p>Dental Plan Software manages your patients and plans with top of the line security and algorithms. You will see all of your statistics of plans and patients all in one place.</p>
                    </li>
                    <li>
                        <div class="feature-list"><img src="/front-end/images/network-icon.png" width="87" height="83" alt="Banner"></div> 
                        <h3><a href="feature-detail.html#specialistNetwork" title="Specialist Network">Specialist Network</a></h3>
                        <p>Refer your patients to the top specialists in the Dental Plan Software network. Specialists are hand chosen and the best in their field. </p>
                    </li>
                    <li>
                        <div class="feature-list"><img src="/front-end/images/email-icon.png" width="73" height="78" alt="Banner"></div> 
                        <h3><a href="feature-detail.html#emailMarketing" title="Email Marketing">Email Marketing</a></h3>
                        <p>We integrate to your practice management system so you can send mass email marketing to your patients to grow your Private Dental Plan base within your practice.</p>
                    </li>
                    <li>
                        <div class="feature-list"><img src="/front-end/images/setup-icon.png" width="77" height="77" alt="Banner"></div>
                        <h3><a href="feature-detail.html#easilySetup" title="Easily Setup Patients">Easily Setup Patients</a></h3>
                        <p>Dental Plan Software makes it simple for you to add your patients to your private dental plan. You can even add family members of your patients and grow your revenue even more.</p>
                    </li>
                    <li>
                        <div class="feature-list"><img src="/front-end/images/schedule-icon.png" width="97" height="68" alt="Banner"></div> 
                        <h3><a href="feature-detail.html#feeSchedule" title="Manage Your Fee Schedule">Manage Your Fee Schedule</a></h3>
                        <p>Specialists can create and manage their own fee schedule to stay competitive in the market. Patients will be able to choose the specialist they like best according to fee schedule and profile.</p>
                    </li>
                    <li>
                        <div class="feature-list"><img src="/front-end/images/card-icon.png" width="82" height="57" alt="Banner"></div> 
                        <h3><a href="feature-detail.html#patientCard" title="Patient ID Cards">Patient ID Cards</a></h3>
                        <p>Dental Plan Software automatically emails your private dental plan ID cards to patients the moment you set them up for a plan. This gives you the professional look of an insurance...</p>
                    </li>
                </ul>
                <div class="green-button started"><a href="/tininsert" title="Sign Up"> Sign Up </a></div>
            	<div class="blue-button clearboth started"><a href="javascript:void(0);" title="Have a Questions?">Have a Questions?</a></div>
            	<div class="denefit-textb">18885085778</div>
            </div>
        </div>
    </div>    
</div>

     
<footer>
    <div class="container">
        <div class="row">
            <div class="footer-menu">
                <ul>
                    <li>Discover</li>
                    <li><a href="javascript:void(0);" title="Better Plans">Better Plans</a></li>
                    <li><a href="javascript:void(0);" title="Better Care">Better Care</a></li>
                    <li><a href="javascript:void(0);" title="Better Experience">Better Experience</a></li>
                </ul>
                <ul>
                    <li>Explore</li>
                    <li><a href="javascript:void(0);" title="Search Doctors">Search Doctors</a></li>
                    <li><a href="javascript:void(0);" title="Search Drugs">Search Plans</a></li>
                    <li><a href="javascript:void(0);" title="Find Forms">Find Forms</a></li>
                </ul>
                <ul>
                    <li>Sign Up</li>
                    <li><a href="/tininsert" title="Get Your Free Quote">Sign Me Up</a></li>
                    <li><a href="javascript:void(0);" title="Talk with a Guide">Talk with a Guide</a></li>
                    <li><a href="javascript:void(0);" title="View Plan Highlights">View Plan Highlights</a></li>
                </ul>
                <ul>
                    <li>Company</li>
                    <li><a href="javascript:void(0);" title="About Us">About Us</a></li>
                    <li><a href="javascript:void(0);" title="Careers">Careers</a></li>
                    <li><a href="/dashboardfront/contact" title="Blog">Contact</a></li>
                </ul>
                <ul>
                    <li>Partners</li>
                    <li><a href="javascript:void(0);" title="Brokers">Brokers</a></li>
                    <li><a href="javascript:void(0);" title="Providers">Providers</a></li>
                    <li><a href="javascript:void(0);" title="Press">Press</a></li>
                </ul>
            </div>
            <div class="terms-frame">
                <div class="bottom-wrapper">
                    <p><span><a href="privacy_policy.html" title="Privacy Policy">Privacy Policy</a> | <a href="terms_use.html" title="Terms of Use">Terms of Use</a></span> &copy; 2016 denefits.com. All Rights Reserved.</p>
                    <ul class="social-links">
                        <li><a href="javascript:void(0);" title="Facebook"><span class="social-icon facebook"></span></a></li>
                        <li><a href="javascript:void(0);" title="Twitter"><span class="social-icon twitter"></span></a></li>
                        <li><a href="javascript:void(0);" title="Linkedin"><span class="social-icon pinterest"></span></a></li>
                        <li><a href="javascript:void(0);" title="Google Plus"><span class="social-icon google"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>    
</footer>
</div>
<script src="/front-end/jscript/jquery.min.js"></script>
<script src="/front-end/jscript/jquery-custom.js"></script> 
</body>
</html>
