<?php
// plan cycle
$plan_billing_cycle[1] = 'Monthly';
$plan_billing_cycle[2] = 'Annually';

$plan_bill_cycle[1] = 'Month';
$plan_bill_cycle[2] = 'Year';
// gender type
$sex[1] = 'Male';
$sex[2] = 'Female';


// plan type
$plan_type[1] = 'Individual';
$plan_type[2] = 'Family';
$plan_type[3] = 'Addon';
use Zend\Session\Container;
 $session = new Container('User');
  $doc_specility_type=  $session->offsetGet('doc_speciality') ;

?>
<header layout="row">
    <?php echo $this->render('dentalheaderlogo.phtml'); ?>
    <div class="searchbar">
        <div class="inner-searchbar"><input type="text" name="search" placeholder="Type the text for search" id="search"></div>
    </div>
     <div class="log-frame" layout-align="start end" ng-controller="headercontrollar" flex>
        <md-switch class="md-primary" md-no-ink ng-model="hasInk" aria-label="No Ink Effects" ng-click="showbtn(switchtext)">
        {{ switchtext }} 
          
        </md-switch>
    </div>
</header>

 <div class="width650 change-password" ng-controller="providerbillingeditcontrollar">
       <fieldset>
          <h2>Billing Information</h2>
            <form name="billingProvider" id="billingProvider">
                  {{  message3  }}  
              <md-input-container class="md-block margin-bottom40">
                  <md-select placeholder="Pay with checking account" ng-model="billing.accounttype">
                      <md-option ng-value="optionno.id" ng-repeat="optionno in paymentoption">{{ optionno.name }}</md-option>
                  </md-select>
              </md-input-container>
               <div ng-if="billing.accounttype==1">
                <md-input-container class="md-block">
                    <label>Bank Account Number</label>
                    <input name="accountno" type="text" ng-model="billing.accountno" ng-pattern='/^(0|[0-9][0-9]*)$/' required>
                    <div ng-show="billingProvider.accountno.$touched">
                      <div class="md-errors-spacer" ng-show="billingProvider.accountno.$error.required">Enter bank account no.</div>
                      <div class="md-errors-spacer" ng-show="billingProvider.accountno.$error.pattern">Only number are allowed .</div>
                   </div>
              </md-input-container>
                <md-input-container class="md-block">
                  <label>Confirm Account Number</label>
                  <input name="conf_account" type="text" ng-pattern="billing.accountno" ng-pattern='/^(0|[0-9][0-9]*)$/' ng-model="billing.conf_account" only-num required>
                  <!--  code for match pattern start       -->  
              <div ng-show="billingProvider.conf_account.$touched">
                  <div class="md-errors-spacer" ng-show="billingProvider.accountno.$error.required">Enter confirm account no.</div>
                  <div class="md-errors-spacer" ng-show="billingProvider.accountno.$error.pattern">Only number are allowed .</div>
                  <div class="md-errors-spacer" ng-show="(billingProvider.conf_account.$viewValue != '' && billingProvider.accountno.$viewValue != '')">
                  <span ng-show="(billingProvider.accountno.$viewValue != billingProvider.conf_account.$viewValue)">Mismatch account no.</span>
              </div>
            </div>
             <!--  code for match pattern end       --> 
                </md-input-container>
                <md-input-container class="md-block">
                    <label>Bank Routing Number</label>
                    <input name="routingno" type="text" ng-pattern='/^(0|[0-9][0-9]*)$/' ng-model="billing.routingno" required>
                    <div ng-show="billingProvider.routingno.$touched">
                      <div class="md-errors-spacer" ng-show="billingProvider.routingno.$error.required">Enter routing no.</div>
                      <div class="md-errors-spacer" ng-show="billingProvider.routingno.$error.pattern">Only number are allowed .</div>
                   </div>
                </md-input-container>
                <md-input-container class="md-block">
                  <label>Confirm Routing Number</label>
                  <input name="conf_routing" type="text"  ng-pattern="billing.routingno" ng-model="billing.conf_routing"  required>
                 
              <!--  code for match pattern start       -->  
              <div ng-show="billingProvider.conf_routing.$touched">
                  <div class="md-errors-spacer" ng-show="billingProvider.routingno.$error.required">Enter confirm routing no.</div>
                  <div class="md-errors-spacer" ng-show="(billingProvider.conf_routing.$viewValue != '' && billingProvider.routingno.$viewValue != '')">
                  <span ng-show="(billingProvider.routingno.$viewValue != billingProvider.conf_routing.$viewValue)">Mismatch routing no.</span>
              </div>
            </div>
             <!--  code for match pattern end       --> 
                </md-input-container>
                
                <md-input-container class="md-block">
                  <label>Account Holder Name</label>
                   <input name="acc_holder_name" type="text" ng-model="billing.acc_holder_name" required>
                   <div ng-show="billingProvider.acc_holder_name.$touched">
                      <div class="md-errors-spacer" ng-show="billingProvider.acc_holder_name.$error.required">Enter account holder name.</div>
                  </div>
               </md-input-container>
              </div>
              <div ng-if="billing.accounttype==2">
                <md-input-container class="md-block">
                  <label>Name on CC</label>
                  <input name="name_on_cc" type="text" ng-model="billing.name_on_cc" required>
                  <div ng-show="billingProvider.name_on_cc.$touched">
                  <div class="md-errors-spacer" ng-show="billingProvider.name_on_cc.$error.required">Enter name on CC.</div>
                </div>
                </md-input-container>
                <md-input-container class="md-block">
                    <label>CC Number</label>
                     <input name="cc_number" type="text" ng-pattern='/^(0|[0-9][0-9]*)$/' ng-maxlength="16" ng-minlength="16"  ng-model="billing.cc_number" required>
                      <div ng-show="billingProvider.cc_number.$touched">
                      <div class="md-errors-spacer" ng-show="billingProvider.cc_number.$error.required">Enter CC number .</div>
                        <div class="md-errors-spacer" ng-show="billingProvider.cc_number.$error.maxlength">Max length should be 16 .</div>
                      <div class="md-errors-spacer" ng-show="billingProvider.cc_number.$error.minlength">Min length should be 16 .</div>
                      <div class="md-errors-spacer" ng-show="billingProvider.cc_number.$error.pattern">Only number are allowed .</div>
                     </div>
                </md-input-container>
                <md-input-container class="md-block">
                <label>Confirm CC number</label>
                <input name="conf_cc_number" type="text" ng-model="billing.conf_cc_number" ng-maxlength="16" ng-minlength="16" ng-pattern="billing.cc_number" required>
                <!--  code for match pattern start       -->  
              <div ng-show="billingProvider.conf_cc_number.$touched">
               <div class="md-errors-spacer" ng-show="billingProvider.conf_cc_number.$error.required">Enter confirm CC number.</div>
                   <div class="md-errors-spacer" ng-show="billingProvider.conf_cc_number.$error.maxlength">Max length should be 16 .</div>
                   <div class="md-errors-spacer" ng-show="billingProvider.conf_cc_number.$error.minlength">Min length should be 16 .</div>
               <div class="md-errors-spacer" ng-show="(billingProvider.conf_cc_number.$viewValue != '' && billingProvider.cc_number.$viewValue != '')">
                  <span ng-show="(billingProvider.cc_number.$viewValue != billingProvider.conf_cc_number.$viewValue)">Mismatch CC number.</span>
              </div>
              </div>
             <!--  code for match pattern end       -->  
                </md-input-container>
                
                <div layout-gt-sm="row">
                  <md-input-container class="md-block" flex-gt-sm>
                        <label>CVC Number</label>
                        <input name="csv_no" type="text" ng-pattern='/^(0|[0-9][0-9]*)$/' ng-maxlength="3" ng-minlength="3"  ng-model="billing.csv_no" required>
                  <div ng-show="billingProvider.csv_no.$touched" required>
                   <div class="md-errors-spacer" ng-show="billingProvider.csv_no.$error.required">Enter CVC number.</div>
                   <div class="md-errors-spacer" ng-show="billingProvider.csv_no.$error.maxlength">Max length should be 3 .</div>
                   <div class="md-errors-spacer" ng-show="billingProvider.csv_no.$error.minlength">Min length should be 3 .</div>
                    <div class="md-errors-spacer" ng-show="billingProvider.csv_no.$error.pattern">Only number are allowed.</div>
                 </div>
                </md-input-container>
              </div>  <!--  row div close here       -->

           
            <div layout-gt-sm="row">
               <md-input-container class="md-block" flex-gt-sm>
                  <label>Exp. Month</label>
                  <md-select ng-model="billing.monthno" placeholder="Select Month">
                        <md-option ng-value="month_name.id" ng-repeat="month_name in monthname">{{ month_name.name }}</md-option>
                 </md-select>

                 <div>
                    <div class="md-errors-spacer"> {{ messagemonth }}</div>
                   
                 </div>
           </md-input-container>
            <md-input-container class="md-block" flex-gt-sm>
              <label>Exp. Year</label>
               <md-select ng-model="billing.exp_year" placeholder="Select Year">
                        <md-option ng-value="year_name.id" ng-repeat="year_name in yearname">{{ year_name.name }}</md-option>
              </md-select>

           <div>
              <div class="md-errors-spacer">{{ messageyear }}</div>
          </div>
         </md-input-container>
        </div>  <!--  row div close here       -->

         </div>  <!--  ng-if div close here       -->
          <div layout="row" layout-align="center center">
            <md-button class="md-warn md-raised save-button next" ng-click="submitBilling(billingProvider)">Save</md-button>
            <?php if($doc_specility_type==3){
            ?>
             <md-button ng-href="/dashboardfront/specilistwelcome" class="md-warn md-raised save-button marginLeft10">Dashboard</md-button>
           <md-button ng-href="/dashboardfront/dashboardsetting" class="md-warn md-raised red-button marginLeft10">Cancel</md-button>
           <?php
         }else{
          ?>
            <md-button ng-href="/dashboardfront/welcome" class="md-warn md-raised save-button marginLeft10">Dashboard</md-button>
           <md-button ng-href="/dashboardfront/dashboardsetting" class="md-warn md-raised red-button marginLeft10">Cancel</md-button>
        <?php
         }
          ?>
        </div>
       </form>
     </fieldset>
    </div>
<script type="text/javascript">  
var app=angular.module('BlankApp', ['ngMaterial']);
app.controller('headercontrollar',function($scope,$http,$window)
{
    $scope.switchtext='logon';
    $scope.showbtn=function(text){
        //alert(text);
        if(text=='logon'){
            $scope.switchtext='logoff';
            $window.location.href = '/logout';
        }
    }   
});
app.controller('providerbillingeditcontrollar', function($scope,$http,$window) 
{ 
    $scope.paymentoption = [                                 // this is doctor type list on billing page 
         { id: 1, name: 'Pay with checking account' },
         { id: 2, name: 'Pay with credit cart' },
         ];
         $scope.monthname= [                                 // this is for month list on billing  
         { id: 1, name: 'January' },
         { id: 2, name: 'February' },
         { id: 3, name: 'March' },
         { id: 4, name: 'April' },
         { id: 5, name: 'May' },
         { id: 6, name: 'June' },
         { id: 7, name: 'July' },
         { id: 8, name: 'August' },
         { id: 9, name: 'September' },
         { id: 10, name: 'October' },
         { id: 11, name: 'November' },
         { id: 12, name: 'December '}
         ];
         $scope.yearname= [                               // this is for year list on billing  
         { id: 2016, name: 2016 },
         { id: 2017, name: 2017 },
         { id: 2018, name: 2018 },
         { id: 2019, name: 2019 },
         { id: 2020, name: 2020 },
         { id: 2021, name: 2021 },
         { id: 2022, name: 2022 },
         { id: 2023, name: 2023 },
         { id: 2024, name: 2024 },
         { id: 2025, name: 2025 },
         { id: 2026, name: 2026 },
         { id: 2027, name: 2027},
         { id: 2028, name: 2029 },
         { id: 2029, name: 2029 },
         { id: 2030, name: 2030 },
         ];
 var doctor_details='<?php  echo $doctor_detailsForId ; ?>';
 var doctor_detailsobject  = angular.fromJson(doctor_details);
 $scope.billing = doctor_detailsobject;
 $scope.submitBilling =function($valid)
    {   
       if($scope.billingProvider.$valid){
          if($scope.billing.monthno==undefined)
         {
            if($scope.billing.accounttype==2)
            {
            $scope.messagemonth =   'Please select month .';  
            return false;
            }
         }
         if($scope.billing.exp_year==undefined)
         { 
            if($scope.billing.accounttype==2)
            {
          $scope.messageyear =   'Please select year .';  
          return false;
            }
         }
          $http.post('/dashboardfront/submitbilling',$scope.billing)
       .success(function(data,status){
          if(data==1)
          $scope.message3="Record updated successfully.";
        })
      }else{
          $scope.message3="Invalid billing form details.";
       }
    } ;







    console.log(doctor_detailsobject);
}); 
</script>
