<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>denefits</title>
<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon">
<link rel="icon" href="/images/favicon.ico" type="image/x-icon">

<!-- Angular Material style sheet -->
<link href="/css/angular-material.css" rel="stylesheet">
<!-- Custom style sheet -->
<link href="/css/custom.css" rel="stylesheet">
</head>
<body ng-app="BlankApp" ng-cloak>
<header layout="row">
 <?php echo $this->render('dentalheaderlogo.phtml'); ?>
    <div class="searchbar">
        <div class="inner-searchbar"><input type="text" name="search" placeholder="Type the text for search" id="search"></div>
    </div>
      <?php echo $this->render('dentalheaderlogin.phtml'); ?>
</header>
    <div id="width1200" class="width1200" ng-controller="refercontroller">
    <div class="grid100 change-password">
    	<div layout="row" layout-align="center center">
            <h2>Specialist Referral Dashboard</h2>
        </div>
        <div layout="row" layout-align="center center">
            <div class="refer-column">
                <ul>
                    <li>
                        <div class="refer-green-column"><img src="/images/refer-icon2.png" width="121" height="92" alt="Refer"><br/><?php echo $this->tot_refer_count; ?><br/>Reffered</div>
                    </li>
                    <li>
                        <div class="refer-blue-column"><img src="/images/acceptance-icon.png" width="72" height="93" alt="Acceptance"><br/><?php echo $this->tot_refer_accepted_count; ?><br/>Pending Acceptance</div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="schedule-table margintop90">
        <md-input-container class="grid350 md-block" style="width:30%;float:left;">
            <md-select placeholder="Email Sents" name="myModel" ng-model="myModel">
                <md-option value="1">Dummy Text</md-option>
                <md-option value="2">Dummy Text</md-option>
                <md-option value="3">Dummy Text</md-option>
            </md-select>
        </md-input-container> 
        <div class="buttons-frame">
                <div class="compaign-frame add-button">
                    <ul>
                        <li class="button dark-green dark-green-shadow"><a href="/dashboardfront/patient" title="New Referral">New Referral</a></li>
                    </ul>
                </div>
        </div>
            <div id="responsive-data" class="responsive-table">
            <table>
                <thead>
                    <tr>
                        <th class="width150">Patient Name</th>
                        <th>Specialist Type</th>
                        <th>Primary Specialist</th>
                        <th>Alternate1 </th>
                        <th>Alternate2 </th>
                        <th>Referral Note</th>
                        <th>Acceptance Status</th>
                        <th colspan="2">Date Referred</th>
                    </tr>
                </thead>

                <tbody>
                <?php
                 foreach($referlisting as $listingdata) 
                  {
                 ?>
                    <tr>
                      <td class="width150"> <?php echo $listingdata['patient_firstname'].' '.$listingdata['patient_lastname'] ;?> </td>
                        <td><span>
                        <?php if($listingdata['dentist_type']=='1')
                        echo "Dentist";
                         if($listingdata['dentist_type']=='2')
                        echo "Pediatric Dentists";
                         if($listingdata['dentist_type']=='3')
                         echo "Other Specialist" ;
                           ?>
                        </span>
                        </td>
                        <td>  <?php echo $listingdata['refer_to_name'] ; ?>  </td>
                        <td>  <?php echo $listingdata['alternate1_name'] ; ?></td>
                        <td>  <?php echo $listingdata['alternate2_name'] ; ?></td>
                        <td class="align-center"> <?php echo $listingdata['comments'] ; ?> <a href="javascript:void(0);" title="Edit"><img src="/images/edit-icon.png" width="26" height="26" alt="Edit"></a></td>
                        <td>
                          <div>
                           <?php  
                           if($listingdata['status']=='0')
                            echo  "Pending" ;
                           if($listingdata['status']=='1')
                            echo  "Accepted" ;
                           if($listingdata['status']=='2')
                            echo  "Decline" ;
                           if($listingdata['status']=='3')
                            echo  "Accepted-But call" ;
                           if($listingdata['status']=='4')
                            echo  "Missed" ;
                           ?>
                           </div>
                        </td>
                        <td> <?php
                         $date=date_create($listingdata['date_reffered']); 
                         echo date_format($date,"d/m/Y"); ?></td>
                        <td class="align-center"><a  href=""  title="Delete" onclick="deleterefer(<?php echo $listingdata['ref_id']; ?>)"><img src="/images/delete-icon.png" width="20" height="25" alt="Delete"></a></td>
                    </tr>
                    <?php
                      }
                    ?>
              </tbody>
            </table>
            </div>
        </div>

    </div>
</div>        
            
<script src="/js/jquery.min.js" type="text/javascript"> </script>
<script type="text/javascript">  
var app=angular.module('BlankApp', ['ngMaterial']);
app.controller('refercontroller', function($scope,$http,$window) 
{ 
 // var referlisting=statesname='<?php echo $referlisting ; ?>';
//  var referlistingobject=angular.fromJson(referlisting); 
 // $scope.referlistingarray  = angular.fromJson(referlistingobject);
}); 
function deleterefer(id)
{ 
  var delmsg= confirm("Are you really want to delete refer.");
  if(delmsg==true){
  url="/dashboardfront/deleterefer/"+id
  $.ajax({
   url:url,
   success:function result(data){
     window.location.assign("/dashboardfront/refer",function(){
     });
   }
 }) ;
}   // if bracket close here 

} // functon bracket close here
</script>

</body>
</html>
