<?php
// gender type
$sex[1] = 'Male';
$sex[2] = 'Female';
?>
<!-- Page content -->
<div id="page-content">
    <!-- Table Styles Header -->
    <div class="content-header">
        <div class="row">
            <div class="col-sm-6">
                <div class="header-section">
                    <h1>Refered Patients&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<small>Total Referrals: <?php echo $totalReferCount;?></small>&nbsp;&nbsp;<small>Accepted: <?php echo $totalReferAcceptedCount;?></small>&nbsp;&nbsp;<small>Rejected: <?php echo $totalRegectedReferCount;?></small></h1>
                </div>
            </div>

        </div>
    </div>
    <!-- END Table Styles Header -->
    <!-- Datatables Block -->
    <!-- Datatables is initialized in js/pages/uiTables.js -->
	<?php if($msg==1000) { ?>
        <div class="row">
			<div class="col-sm-12">
				<div class="alert alert-success alert-dismissable">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
						<p><?php echo "Patient Accepted";?></p>
				</div>
			</div>
		</div>
	<?php } else if($msg==2000) { ?>
        <div class="row">
			<div class="col-sm-12">
				<div class="alert alert-danger alert-dismissable">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
						<p><?php echo "Patient Rejected";?></p>
				</div>
			</div>
		</div>
	<?php } ?>
    <div class="block full">
        <div class="table-responsive">
            <table id="example-datatable" class="table table-striped table-bordered table-vcenter">
                <thead>
                    <tr>
                        <th class="text-center" style="width: 30px;">ID</th>
                        <th>Name</th>
                        <th>Age</th>
                        <th>Sex</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Referred By</th>
                        <th>Comments</th>
                        <th class="text-center" style="width: 85px;"><i class="fa fa-flash"></i></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $labels['0']['class'] = "label-danger";
                    $labels['0']['text'] = "Inactive";
                    $labels['1']['class'] = "label-success";
                    $labels['1']['text'] = "Active";
					// get list of plans for this doctor
				    foreach($ReferralsPatientListing as $pat_r)
                    {
						if($pat_r['patient_phone']) 
							$phone[] = $pat_r['patient_phone'];
						if($pat_r->patient_mobile) 
							$phone[] = $pat_r['patient_mobile'];

					?>
                    <tr>
                        <td class="text-center"><?php echo $pat_r['patient_id']; ?></td>
                        <td><?php echo $pat_r['patient_firstname'].' '.$pat_r['patient_lastname']; ?></td>
                        <td><?php echo (date('Y')-date('Y',strtotime($pat_r['patient_dob']))); ?></td>
                        <td><?php echo $sex[$pat_r['patient_sex']]; ?></td>
                        <td><?php echo $pat_r['patient_email']; ?></td>
                        <td><?php if(is_array($phone)) { echo implode(' / ',$phone); } else echo $phone; ?></td>
                        <?php
                            foreach($doctorDetails as $doctorDetailsvalue) 
                             {
                              if($doctorDetailsvalue['doc_id']==$pat_r['refer_by'])
                                {
                                 $referred_to = $doctorDetailsvalue['doc_firstname'].' '.$doctorDetailsvalue['doc_lastname'] ;
                              ?>
                          <td><?php echo $referred_to; ?></td>
                               <?php
                               }
                             }
                          ?>
                        <td><?php echo $pat_r['comments']; ?></td>
                        <td class="text-center">
							<a href="/dashboardfront/specilistreferlist/<?php echo $pat_r['ref_id'];?>/1000" data-toggle="tooltip" title="Accept Patient" class="btn btn-effect-ripple btn-xs btn-info"><i class="fa fa-check"></i></a>
                            <a href="/dashboardfront/specilistreferlist/<?php echo $pat_r->ref_id;?>/2000" data-toggle="tooltip" title="Reject Patient" class="btn btn-effect-ripple btn-xs btn-danger"><i class="fa fa-times"></i></a>
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
    <!-- END Datatables Block -->
</div>
<!-- END Page Content -->



<!-- Load and execute javascript code used only in this page -->
<script src="/js/pages/uiTables.js"></script>
<script>$(function(){ UiTables.init(); });</script>
