
<!-- Page content -->
<div id="page-content">
    <!-- Table Styles Header -->
    <div class="content-header">
        <div class="row">
            <div class="col-sm-6">
                <div class="header-section">
                    <h1>Manage Services</h1>
                </div>
            </div>
            <div class="col-sm-6 hidden-xs">
                <div class="header-section">
                    <ul class="breadcrumb breadcrumb-top">
                        <li><a href="<?php echo $this->url('dashboardfront',array('action'=>'specialistsplservicesadd')) ;?>" class="btn btn-effect-ripple btn-primary" data-toggle="tooltip" data-placement="left" title="" style="overflow: hidden; position: relative;" data-original-title="Create new plan">Add new service</a></li>
                    </ul>
                </div>
            </div>

        </div>
    </div>
    <!-- END Table Styles Header -->
    <!-- Datatables Block -->
    <!-- Datatables is initialized in js/pages/uiTables.js -->
	<?php if($del_message) { ?>
        <div class="row">
			<div class="col-sm-12">
				<div class="alert alert-success alert-dismissable">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
						<h4><strong>Success</strong></h4>
						<p>Record Deleted successfully!</p>
				</div>
			</div>
		</div>
	<?php } ?>

    <div class="block full">
        <div class="table-responsive">
            <table id="example-datatable" class="table table-striped table-bordered table-vcenter">
                <thead>
                    <tr>
                        <th class="text-center" style="width: 50px;">ID</th>
                        <th>Service Name</th>
                        <th>Price</th>
                        <th class="text-center" style="width: 75px;"><i class="fa fa-flash"></i></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
					// get list of spl services
					foreach($splserviceDetails as $splservice_r) { 

					?>
                    <tr>
                        <td class="text-center"><?php echo $splservice_r['service_id']; ?></td>
                        <td><?php echo $splservice_r['service_type']; ?></td>
                        <td><?php echo "$".$splservice_r['price']; ?></td>
                        <td class="text-center">
							<a href="<?php echo $this->url('dashboardfront',array('action'=>'specialistsplservicesviewdetails','id'=>$splservice_r['service_id'])) ;?>" data-toggle="tooltip" title="View Service" class="btn btn-effect-ripple btn-xs btn-info"><i class="fa fa-laptop"></i></a>
                            <a href="<?php echo $this->url('dashboardfront',array('action'=>'specialistsplservicesadd','id'=>$splservice_r['service_id'])) ;?>" data-toggle="tooltip" title="Edit Service" class="btn btn-effect-ripple btn-xs btn-success"><i class="fa fa-pencil"></i></a>
                            <a href="/dashboardfront/specilistdelservices/<?php echo $splservice_r['service_id'];?>" data-toggle="tooltip" title="Delete Service" class="btn btn-effect-ripple btn-xs btn-danger" onclick="return confirm('Are you sure you want to delete this Service');"><i class="fa fa-times"></i></a>
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
    <!-- END Datatables Block -->
</div>
<!-- END Page Content -->

<script src="/js/pages/uiTables.js"></script>
<script>$(function(){ UiTables.init(); });</script>
<script type="text/javascript">$.fn.dataTable.ext.errMode = 'none';</script>

