<!DOCTYPE html>
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">

        <title>Dental Plan Software</title>

        <meta name="description" content="AppUI Frontend is a Responsive Bootstrap Site Template created by pixelcave and added as a bonus in AppUI Admin Template package">
        <meta name="author" content="pixelcave">
        <meta name="robots" content="noindex, nofollow">

        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">

        <!-- Icons -->
        <!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->
        <link rel="shortcut icon" href="/front_img/favicon.png">
        <link rel="apple-touch-icon" href="/front_img/icon57.png" sizes="57x57">
        <link rel="apple-touch-icon" href="/front_img/icon72.png" sizes="72x72">
        <link rel="apple-touch-icon" href="/front_img/icon76.png" sizes="76x76">
        <link rel="apple-touch-icon" href="/front_img/icon114.png" sizes="114x114">
        <link rel="apple-touch-icon" href="/front_img/icon120.png" sizes="120x120">
        <link rel="apple-touch-icon" href="/front_img/icon144.png" sizes="144x144">
        <link rel="apple-touch-icon" href="/front_img/icon152.png" sizes="152x152">
        <link rel="apple-touch-icon" href="/front_img/icon180.png" sizes="180x180">
        <!-- END Icons -->

        <!-- Stylesheets -->
        <!-- Bootstrap is included in its original form, unaltered -->
        <link rel="stylesheet" href="/front_css/bootstrap.min.css">

        <!-- Related styles of various icon packs and plugins -->
        <link rel="stylesheet" href="/front_css/plugins.css">

        <!-- The main stylesheet of this template. All Bootstrap overwrites are defined in here -->
        <link rel="stylesheet" href="/front_css/main.css">

        <!-- The themes stylesheet of this template (for using specific theme color in individual elements - must included last) -->
        <link rel="stylesheet" href="/front_css/themes.css">
        <!-- END Stylesheets -->

        <!-- Modernizr (browser feature detection library) -->
        <script src="/front_js/vendor/modernizr-2.8.3.min.js"></script>
    </head>
    <body>
        <!-- Page Container -->
        <!-- In the PHP version you can set the following options from inc/config file -->
        <!-- 'boxed' class for a boxed layout -->
        <div id="page-container" class="boxed">
              <!-- Site Header -->
            <header>
                <div class="container">
                    <div class="site-logo"><a href="index.php" class="site-logo"><img src="/front_img/logo1.png" alt="Logo"></a></div>
                    <!-- Site Logo -->
                  
                    <!-- END Site Logo -->

                    <!-- Site Navigation -->
                    <nav>
                        <!-- Menu Toggle -->
                        <!-- Toggles menu on small screens -->
                        <a href="javascript:void(0)" class="btn btn-default site-menu-toggle visible-xs visible-sm">Menu</a>
                        <!-- END Menu Toggle -->

                        <!-- Main Menu -->
                        <ul class="site-nav">
                          <li>
                                <a href="/" class="active">Home</a>
                            </li>
                            <li>
                                <a href="/dashboardfront/aboutus">About Us</a>
                            </li>
                            <li>
                                <a href="/dashboardfront/features">Features</a>
                            </li>
                            <li>
                                <a href="/dashboardfront/pricing">Pricing</a>
                            </li>
                           <!-- <li>
                                <a href="specialists.html">Specialists</a>
                            </li>-->
                            <li>
                                <a href="/dashboardfront/contact">Contact Us</a>
                            </li>
                         <!--  <li>
                                <a href="javascript:void(0)" class="site-nav-sub"><i class="fa fa-angle-down site-nav-arrow"></i>More</a>
                                <ul>
                                    <li>
                                        <a href="about.html">About Us</a>
                                    </li>
                                    <li>
                                         <a href="faq.html">FAQ</a>
                                    </li>
                                    <li>
                                        <a href="blog.html">Blog</a>
                                    </li>
                                     <li>
                                        <a href="revenue.html">Potential Revenue</a>
                                    </li>
                                </ul>
                            </li>-->
                            <li>
                                <a href="https://dentalplansoftware.com/login.php" class="featured">Sign In<i class="fa fa-arrow-right"></i></a>
                            </li>
                        </ul>
                        <!-- END Main Menu -->
                    </nav>
                    <!-- END Site Navigation -->
                </div>
            </header>
            <!-- END Site Header -->

            <!-- Intro -->
            <section class="site-section site-section-top site-section-light themed-background-dark">
                <div class="container">
                    <h1 class="text-center animation-fadeInQuickInv"><strong>The solution to all your insurance problems.</strong></h1>
                </div>
            </section>
            <!-- END Intro -->

            <!-- Team Member 1 -->
            <section class="site-content site-section overflow-hidden border-bottom">
                <div class="container">
                    <div class="row row-items" style="height:600px;" align="center">
                            
                            
                            <p style="font-size:22px; line-height:40px;"><br>Thanks to submit the form. We will contact you soon</p>
                    
                       
                    </div>
                </div>
            </section>
            <!-- END Team Member 1 -->
            <!-- Footer -->
            <footer class="site-footer site-section site-section-light">
                <div class="container">
                    <!-- Footer Links -->
                    <div class="row">
                        <div class="col-sm-4">
                            <h4 class="footer-heading">Company</h4>
                            <ul class="footer-nav ul-breath list-unstyled">
                                <li><a href="about.html">About Us</a></li>
                                <li><a href="features.html">Features</a></li>
                                <li><a href="pricing.html">Pricing</a></li>
                                <li><a href="terms_condition.html">Terms &amp; Conditions</a></li>
                                <li><a href="privacy_policy.html">Privacy Policy</a></li>
                            </ul>
                        </div>
                        <div class="col-sm-4">
                            <h4 class="footer-heading">Need support?</h4>
                            <ul class="footer-nav footer-nav-links list-inline">
                                <li><a href="contact.html"><i class="fa fa-fw fa-book"></i> Contact Us</a></li>
                            </ul>
                            <h4 class="footer-heading">We are social!</h4>
                            <ul class="footer-nav footer-nav-links list-inline">
                                <li><a href="javascript:void(0)" class="social-facebook" data-toggle="tooltip" title="Like our Facebook page"><i class="fa fa-fw fa-facebook"></i></a></li>
                                <li><a href="javascript:void(0)" class="social-twitter" data-toggle="tooltip" title="Follow us on Twitter"><i class="fa fa-fw fa-twitter"></i></a></li>
                                <li><a href="javascript:void(0)" class="social-google-plus" data-toggle="tooltip" title="Like our Google+ page"><i class="fa fa-fw fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                        <div class="col-sm-4">
                            <h4 class="footer-heading">Newsletter</h4>
                            <form action="/dashboardfront/suscribe" method="post" class="form-inline">
                                <div class="form-group">
                                    <label class="sr-only" for="register-email">Your Email</label>
                                    <div class="input-group">
                                        <input type="email" id="register-email" name="register-email" class="form-control" placeholder="Your Email..">
                                        <span class="input-group-btn">
                                            <button type="submit" class="btn btn-primary">Subscribe</button>
                                        </span>
                                    </div>
                                </div>
                            </form>
                            <h4 class="footer-heading"><a href="contact.html" style="color:#FFC">Check Demo</a></h4>
                            &copy; <em>2016</em>Crafted with <i class="fa fa-heart text-danger"></i> by <a href="http://docmate.com/" style="color:#FFC">A1 Healthcare Technologies</a>
                        </div>
                    </div>
                    <!-- END Footer Links -->
                </div>
            </footer>
            <!-- END Footer -->
        </div>
        <!-- END Page Container -->

        <!-- Scroll to top link, initialized in front_js/app.js - scrollToTop() -->
        <a href="#" id="to-top"><i class="fa fa-arrow-up"></i></a>

        <!-- jQuery, Bootstrap, jQuery plugins and Custom JS code -->
        <script src="/front_js/vendor/jquery-2.1.4.min.js"></script>
        <script src="/front_js/vendor/bootstrap.min.js"></script>
        <script src="/front_js/plugins.js"></script>
        <script src="/front_js/app.js"></script>
    </body>
</html>