<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, height=device-height">
<meta name="viewport" content="width=device-width; initial-scale=1.0">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<title>Denefits</title>
<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
<link rel="icon" href="/front-end/images/favicon.ico" type="image/x-icon">

<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400;300' rel='stylesheet' type='text/css'>

<link href="/front-end/css/style.css" rel="stylesheet">
</head>
<body>
<div class="wrapper">
<header>
	<div class="logo"><a href="/" title="denefits"><img src="/front-end/images/logo.png" width="260" height="79" alt="Logo"></a></div>  
    <div class="menu">
    	<div class="green-button"><a href="javascript:void(0);" title="Get Your Plan">Get Your Plan</a></div>
        <div class="icon-close">
            <img src="/front-end/images/close.png" width="22" height="22" alt="Close">
        </div>
        <div class="denefit-text">18885085778</div>
       
        <ul>
            <li><a href="/dashboardfront/riskreferrals" title="Risk Refferals">No Risk Refferals</a></li>
            <li><a href="/dashboardfront/doctordashboard" title="Doctor Dashboard">Patients</a></li>
            <li><a href="/dashboardfront/features" title="Feature">Features</a></li>
            <li><a href="/dashboardfront/pricing" title="Pricing">Pricing</a></li>
            <li><a href="/dashboardfront/contact" title="Contact Us">Contact Us</a></li>
            <li><a href="/dashboardfront/workwithus" title="Work With Us">Work With Us</a></li> 
        </ul>

    </div>
    <div class="icon-menu">
        <ul>
        	<li><a href="javascript:void(0);" title="Patients"><span class="provider-icon"></span>Patients</a></li>
            <li><a href="/admin/1" title="Login"><span class="login-icon"></span>Login</a></li>
            <li class="burger-menu"><i class="fa fa-bars"></i> <span class="menu-text">Menu</span></li>
        </ul>
    </div>
    <div id="menu">
    	<div class="logo"><a href="index.html" title="denefits"><img src="/front-end/images/logo.png" width="260" height="79" alt="Logo"></a></div>  
        <div class="icon-menu">
            <ul>
                <li><a href="javascript:void(0);" title="Provider"><span class="talk-icon"></span>Talk With a Guide</a></li>
                <li class="quote-button"><a href="/tininsert" title="Get a Quote">Sign Up</a></li>
            </ul>
        </div>
    </div>
</header>
<div class="container">
	<div class="row">
		<div class="banner">
        	<h1><span>Healthcare is broken.</span><br/>Help us fix it.</h1>
            <div class="green-button started"><a href="javascript:void(0);" title="See Open Jobs">See Open Jobs</a></div>
        </div>
    </div>
</div>
<div class="grid100">
    <div class="container">
        <div class="row">
            <div class="cost-process">
                <div class="zip-wrapper">
                    <h2>Solve hard problems.</h2>
                    <p>The best people should work on the hardest problems. We're using engineering, data analysis, and more to create better healthcare experiences for members and push the industry forward.</p>
                </div>
                <ul>
                    <li>
                        <div class="process-banner"><img src="/front-end/images/build-banner.png" width="153" height="135" alt="Banner"></div>
                        <h3>Bulid</h3>
                        <h4>Engineering, Product, and Data</h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis arcu sit amet dui lacinia, at pretium massa congue. Etiam </p>
                        <a href="javascript:void(0);" title="Learn More">Learn More</a>
                    </li>
                    <li>
                        <div class="process-banner"><img src="/front-end/images/grow-banner.png" width="160" height="135" alt="Banner"></div> 
                        <h3>Grow</h3>
                        <h4>Social Media, Marketing</h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis arcu sit amet dui lacinia, at pretium massa congue. Etiam </p>
                        <a href="javascript:void(0);" title="Learn More">Learn More</a>
                    </li>
                    <li>
                        <div class="process-banner"><img src="/front-end/images/care-banner.png" width="127" height="135" alt="Banner"></div> 
                        <h3>Care</h3>
                        <h4>People Ops, and Member Service</h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis arcu sit amet dui lacinia, at pretium massa congue. Etiam </p>
                        <a href="javascript:void(0);" title="Learn More">Learn More</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>    
</div>

     
<footer>
    <div class="container">
        <div class="row">
            <div class="footer-menu">
                 <ul>
                    <li>Discover</li>
                    <li><a href="javascript:void(0);" title="Better Plans">Better Plans</a></li>
                    <li><a href="javascript:void(0);" title="Better Care">Better Care</a></li>
                    <li><a href="javascript:void(0);" title="Better Experience">Better Experience</a></li>
                </ul>
                <ul>
                    <li>Explore</li>
                    <li><a href="javascript:void(0);" title="Search Doctors">Search Doctors</a></li>
                    <li><a href="javascript:void(0);" title="Search Drugs">Search Plans</a></li>
                    <li><a href="javascript:void(0);" title="Find Forms">Find Forms</a></li>
                </ul>
                <ul>
                    <li>Sign Up</li>
                    <li><a href="/tininsert" title="Get Your Free Quote">Sign Me Up</a></li>
                    <li><a href="javascript:void(0);" title="Talk with a Guide">Talk with a Guide</a></li>
                    <li><a href="javascript:void(0);" title="View Plan Highlights">View Plan Highlights</a></li>
                </ul>
                <ul>
                    <li>Company</li>
                    <li><a href="javascript:void(0);" title="About Us">About Us</a></li>
                    <li><a href="javascript:void(0);" title="Careers">Careers</a></li>
                    <li><a href="/dashboardfront/contact" title="Blog">Contact</a></li>
                </ul>
                <ul>
                    <li>Partners</li>
                    <li><a href="javascript:void(0);" title="Brokers">Brokers</a></li>
                    <li><a href="javascript:void(0);" title="Providers">Providers</a></li>
                    <li><a href="javascript:void(0);" title="Press">Press</a></li>
                </ul>
            </div>
            <div class="terms-frame">
                <div class="bottom-wrapper">
                    <p><span><a href="privacy_policy.html" title="Privacy Policy">Privacy Policy</a> | <a href="terms_use.html" title="Terms of Use">Terms of Use</a></span> &copy; 2016 denefits.com. All Rights Reserved.</p>
                    <ul class="social-links">
                        <li><a href="javascript:void(0);" title="Facebook"><span class="social-icon facebook"></span></a></li>
                        <li><a href="javascript:void(0);" title="Twitter"><span class="social-icon twitter"></span></a></li>
                        <li><a href="javascript:void(0);" title="Linkedin"><span class="social-icon pinterest"></span></a></li>
                        <li><a href="javascript:void(0);" title="Google Plus"><span class="social-icon google"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>    
</footer>
</div>
<script src="/front-end/jscript/jquery.min.js"></script>
<script src="/front-end/jscript/jquery-custom.js"></script> 
</body>
</html>
