<?php echo $this->doctype(); 
use Zend\Session\Container;
$session = new Container('User');
$userdatails =array();
$userdatails= $session->offsetGet('userdetail');

?>
<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>denefits</title>
<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
<link rel="icon" href="images/favicon.ico" type="image/x-icon">

<!-- Angular Material style sheet -->
<link href="css/angular-material.css" rel="stylesheet">
<!-- Custom style sheet -->
<link href="css/custom.css" rel="stylesheet">
</head>
<body class="dashboard" ng-app="BlankApp" ng-cloak>

<!-- header code will start here    -->
                   <?php 
                     $session = new Container('User');
                     if($session->offsetExists('email'))
                     { 
                     echo $this->partial('dashboard_header.phtml');  
                     }
                     ?>
<!-- header code will end here    -->
<!-- contant start here    -->
      <?php   echo $this->content;?>
<!-- contant end here    -->
<!-- Angular Material requires Angular.js Libraries -->
<script src="/1jscript/angular.min.js"></script>
<script src="/jscript/angular-animate.min.js"></script>
<script src="/jscript/angular-aria.min.js"></script>
<script src="/jscript/angular-messages.min.js"></script>

<!-- Angular Material Library -->
<script src="jscript/angular-material.min.js"></script> 

<!-- Your application -->
<script type="text/javascript">    
/**
 * You must include the dependency on 'ngMaterial' 
 */
angular.module('BlankApp', ['ngMaterial']);
</script>
<script src="jscript/jquery-1.9.1.min.js"></script>
<script>
$(document).ready(function(){
  $(".log-frame li.profile a").click(function() {
      $(".dropdown-menu").toggle("slow");
  });
});
</script>
</body>
</html>

