<?php echo $this->doctype(); 
//$stripepath= $_SERVER['DOCUMENT_ROOT']."/stripe/stripephp340/init.php";
//require_once($stripepath);
use Zend\Session\Container;
$session = new Container('User');
$userdatails =array();
$userdatails= $session->offsetGet('userdetail');

?>
<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>denefits</title>
<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon">
<link rel="icon" href="/images/favicon.ico" type="image/x-icon">

<!-- Angular Material style sheet -->
<link href="/css/angular-material.css" rel="stylesheet">
<!-- Custom style sheet -->

</head>

<!-- header code will start here    -->
                   <?php 
                     $session = new Container('User');
                     if($session->offsetExists('email'))
                     {
                     ?>
                     <link href="/css/custom.css" rel="stylesheet">
                     <script src="/jscript/angular.min.js"></script>
                     <script src="/jscript/angular-animate.min.js"></script>
                     <script src="/jscript/angular-aria.min.js"></script>
                     <script src="/jscript/angular-messages.min.js"></script>

<!-- Angular Material Library -->
                     <script src="/jscript/angular-material.min.js"></script> 
                     <body class="" ng-app="BlankApp" ng-cloak>
                     <?php
                     echo $this->partial('dashboard_header.phtml');  
                     }else{
                     ?>
                     <body ng-app="BlankApp" ng-cloak>
                     <?php
                      }
                     ?>

<!-- header code will end here    -->
<!-- contant start here    -->
      <?php   echo $this->content;?>
<!-- contant end here    -->
<!-- Angular Material requires Angular.js Libraries -->


    <?php 
                     $session = new Container('User');
                     if($session->offsetExists('email'))
                     {
                     ?>
                     <link href="/css/custom.css" rel="stylesheet">
                   <!-- Your application -->
<!-- Angular Material requires Angular.js Libraries -->
<script src="jscript/angular.js"></script>
<script src="jscript/angular-animate.min.js"></script>
<script src="jscript/angular-aria.min.js"></script>
<script src="jscript/angular-messages.min.js"></script>

<!-- Angular Material Library -->
<script src="jscript/angular-material.min.js"></script> 

<!-- Your application -->

<script src="jscript/jquery-1.9.1.min.js"></script>
<script>
$(document).ready(function(){
  $(".log-frame li.profile a").click(function() {
	  $(".dropdown-menu").toggle("slow");
  });
});
</script>
<?php
}
?>


</body>
</html>

