<?php echo $this->doctype(); 
use Zend\Session\Container;
?>
<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>denefits</title>
<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon">
<link rel="icon" href="/images/favicon.ico" type="image/x-icon">

<!-- Angular Material style sheet -->

<link href="/css/angular-material.css" rel="stylesheet">
<!-- Custom style sheet -->
<link href="/css/custom.css" rel="stylesheet">
<script src="/jscript/angular.min.js"></script>
</head>
<body ng-app="BlankApp" ng-cloak>

<!--   here header  menu  start here           -->
            <?php 
                     $session = new Container('User');
                     if($session->offsetExists('email'))
                    { 
						?>
						<!-- Angular Material requires Angular.js Libraries -->
<script src="/jscript/angular.js"></script>
<script src="/jscript/angular-animate.min.js"></script>
<script src="/jscript/angular-aria.min.js"></script>
<script src="/jscript/angular-messages.min.js"></script>

<!-- Angular Material Library -->
<script src="/jscript/angular-material.min.js"></script> 
                     <?php
                 //    echo $this->partial('header.phtml');  
                     }
                     ?>
<!--   here header  menu  end here           -->



       <?php   echo $this->content;?>
   
<!--
    <div class="grid100 change-password">
        <h2>How would like to Logon</h2>
        <form name="userForm">
            <md-input-container class="md-block">
                <label>User name</label>
                <input name="user" type="text" ng-model="user.userName">
            </md-input-container>
            <md-input-container class="md-block">
                <label>Password</label>
                <input name="password" type="password" ng-model="password.password">
            </md-input-container>
            <md-input-container class="md-block">
                <label>Confirm Password</label>
                <input name="password" type="password" ng-model="confirm.password">
            </md-input-container>
            <md-button class="md-warn md-raised save-button">Next</md-button>
        </form>
    </div>
    -->







</body>
</html>
