<?php
$adminurl= $_SERVER['REQUEST_URI'];
?>
        <!-- Alternative Sidebar -->
<div aria-hidden="true" tabindex="-1" id="sidebar-alt">
    <!-- Toggle Alternative Sidebar Button (visible only in static layout) -->
    <a onclick="App.sidebar('toggle-sidebar-alt');" id="sidebar-alt-close" href="javascript:void(0)"><i class="fa fa-times"></i></a>

    <!-- Wrapper for scrolling functionality -->
    <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 383px;"><div id="sidebar-scroll-alt" style="overflow: hidden; width: auto; height: 383px;">
        <!-- Sidebar Content -->
        <div class="sidebar-content">
            <!-- Profile -->
            <div class="sidebar-section">
                <h2 class="text-light">Profile</h2>
                <form onsubmit="return false;" class="form-control-borderless" method="post" action="index.php">
                    <div class="form-group">
                        <label for="side-profile-name">Name</label>
                        <input type="text" value="John Doe" class="form-control" name="side-profile-name" id="side-profile-name">
                    </div>
                    <div class="form-group">
                        <label for="side-profile-email">Email</label>
                        <input type="email" value="john.doe@example.com" class="form-control" name="side-profile-email" id="side-profile-email">
                    </div>
                    <div class="form-group">
                        <label for="side-profile-password">New Password</label>
                        <input type="password" class="form-control" name="side-profile-password" id="side-profile-password">
                    </div>
                    <div class="form-group">
                        <label for="side-profile-password-confirm">Confirm New Password</label>
                        <input type="password" class="form-control" name="side-profile-password-confirm" id="side-profile-password-confirm">
                    </div>
                    <div class="form-group remove-margin">
                        <button onclick="App.sidebar('close-sidebar-alt');" class="btn btn-effect-ripple btn-primary" type="submit" style="overflow: hidden; position: relative;">Save</button>
                    </div>
                </form>
            </div>
            <!-- END Profile -->

            <!-- Settings -->
            <div class="sidebar-section">
                <h2 class="text-light">Settings</h2>
                <form onsubmit="return false;" class="form-horizontal form-control-borderless" method="post" action="index.php">
                    <div class="form-group">
                        <label class="col-xs-7 control-label-fixed">Notifications</label>
                        <div class="col-xs-5">
                            <label class="switch switch-success"><input type="checkbox" checked=""><span></span></label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-7 control-label-fixed">Public Profile</label>
                        <div class="col-xs-5">
                            <label class="switch switch-success"><input type="checkbox" checked=""><span></span></label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-7 control-label-fixed">Enable API</label>
                        <div class="col-xs-5">
                            <label class="switch switch-success"><input type="checkbox"><span></span></label>
                        </div>
                    </div>
                    <div class="form-group remove-margin">
                        <button onclick="App.sidebar('close-sidebar-alt');" class="btn btn-effect-ripple btn-primary" type="submit" style="overflow: hidden; position: relative;">Save</button>
                    </div>
                </form>
            </div>
            <!-- END Settings -->
        </div>
        <!-- END Sidebar Content -->
    </div><div class="slimScrollBar" style="background: rgb(187, 187, 187) none repeat scroll 0% 0%; width: 3px; position: absolute; top: 0px; opacity: 0.4; display: none; border-radius: 7px; z-index: 99; right: 1px; height: 877px;"></div><div class="slimScrollRail" style="width: 3px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(51, 51, 51) none repeat scroll 0% 0%; opacity: 1; z-index: 90; right: 1px;"></div></div>
    <!-- END Wrapper for scrolling functionality -->
</div>
<!-- END Alternative Sidebar -->

        <!-- Main Sidebar -->
<div id="sidebar">
    <!-- Sidebar Brand -->
    <div class="themed-background" id="sidebar-brand">
        <a class="sidebar-title" href="index.php">
           <img width="100%" height="100%" alt="Dental Plan" src="/img/logo.png"><!-- <i class="fa fa-cube"></i> <span class="sidebar-nav-mini-hide">App<strong>UI</strong></span>-->
        </a>
    </div>
    <!-- END Sidebar Brand -->

    <!-- Wrapper for scrolling functionality -->
    <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 383px;"><div id="sidebar-scroll" style="overflow: hidden; width: auto; height: 383px;">
        <!-- Sidebar Content -->
        <div class="sidebar-content">
                        <!-- Sidebar Navigation -->
            <ul class="sidebar-nav">
                <li>
                    <a <?php  if($adminurl=='/dashboard') { ?> class=" active" <?php } ?> href="<?php echo $this->url('dashboard',array('action'=>'index'))  ?>"><i class="gi gi-compass sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Dashboard</span></a>
                </li>
                                                                <li>
                    <a <?php if($adminurl=='/dashboard/doctorgrid') { ?> class=" active" <?php } ?>  href="<?php echo $this->url('dashboard',array('action'=>'doctorgrid')) ; ?>"><i class="fa fa-rocket sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Manage Doctors</span></a>
                                    </li>
                                                                <li>
                    <a <?php if($adminurl=='/dashboard/specialistdoctorgrid') { ?> class=" active" <?php } ?>  href="<?php echo $this->url('dashboard',array('action'=>'specialistdoctorgrid')) ; ?>"><i class="fa fa-plane sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Manage Specialist</span></a>
                                    </li>
                                                                <li>
                    <a <?php if($adminurl=='/dashboard/reports') { ?> class=" active" <?php } ?>  href="<?php echo $this->url('dashboard',array('action'=>'reports')) ; ?>"><i class="fa fa-calendar sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Reports</span></a>
                                    </li>
                                                                <li>
                    <a <?php if($adminurl=='/dashboard/support') { ?> class=" active" <?php } ?> href="<?php echo $this->url('dashboard',array('action' =>'support')); ?>"><i class="gi gi-more_items sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Support</span></a>
                                    </li>
                                                            
                        <li>
                    <a <?php if($adminurl=='/dashboard/changepassword') { ?> class=" active" <?php } ?> href="<?php echo $this->url('dashboard',array('action'=>'changepassword')) ; ?>"><i class="fa fa-key sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Change Password</span></a>
                     </li>
                                                                <li>
                    <a <?php if($adminurl=='/dashboard/changeusername') { ?> class=" active" <?php } ?> href="<?php echo  $this->url('dashboard',array('action'=>'changeusername')); ?>"><i class="fa fa-key sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Change Username</span></a>
                                    </li>
                                            </ul>
  
        </div>
        <!-- END Sidebar Content -->
    </div><div class="slimScrollBar" style="background: rgb(187, 187, 187) none repeat scroll 0% 0%; width: 3px; position: absolute; top: 0px; opacity: 0.4; display: none; border-radius: 7px; z-index: 99; right: 1px; height: 383px;"></div><div class="slimScrollRail" style="width: 3px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(51, 51, 51) none repeat scroll 0% 0%; opacity: 1; z-index: 90; right: 1px;"></div></div>
    <!-- END Wrapper for scrolling functionality -->

    <!-- Sidebar Extra Info -->
    <!--<div id="sidebar-extra-info" class="sidebar-content sidebar-nav-mini-hide">
        <div class="push-bit">
            <span class="pull-right">
                <a href="javascript:void(0)" class="text-muted"><i class="fa fa-plus"></i></a>
            </span>
            <small><strong>78 GB</strong> / 100 GB</small>
        </div>
        <div class="progress progress-mini push-bit">
            <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="78" aria-valuemin="0" aria-valuemax="100" style="width: 78%"></div>
        </div>
        <div class="text-center">
            <small>Crafted with <i class="fa fa-heart text-danger"></i> by <a href="http://goo.gl/vNS3I" target="_blank">pixelcave</a></small><br>
            <small><span id="year-copy"></span> &copy; <a href="http://goo.gl/RcsdAh" target="_blank">AppUI 2.4</a></small>
        </div>
    </div>-->
    <!-- END Sidebar Extra Info -->
</div>
<!-- END Main Sidebar -->